### PR TITLE
fix(templates): match local behaviour of templates with prod

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
Getting these: 
```
>> server/templates/pages/dist/ar/404.html: (E005), line 2, col 11, the `dir` attribute is not quoted
>> server/templates/pages/dist/ar/404.html: (E005), line 2, col 20, the `lang` attribute is not quoted
>> server/templates/pages/dist/ar/500.html: (E005), line 2, col 11, the `dir` attribute is not quoted
>> server/templates/pages/dist/ar/500.html: (E005), line 2, col 20, the `lang` attribute is not quoted
>> server/templates/pages/dist/ar/502.html: (E005), line 2, col 11, the `dir` attribute is not quoted
>> server/templates/pages/dist/ar/502.html: (E005), line 2, col 20, the `lang` attribute is not quoted
>> server/templates/pages/dist/ar/503.html: (E005), line 2, col 11, the `dir` attribute is not quoted
>> server/templates/pages/dist/ar/503.html: (E005), line 2, col 20, the `lang` attribute is not quoted
>> server/templates/pages/dist/ar/index.html: (E005), line 2, col 11, the `dir` attribute is not quoted
>> server/templates/pages/dist/ar/index.html: (E005), line 2, col 20, the `lang` attribute is not quoted
>> server/templates/pages/dist/ar/privacy.html: (E005), line 2, col 11, the `dir` attribute is not quoted
>> server/templates/pages/dist/ar/privacy.html: (E005), line 2, col 20, the `lang` attribute is not
```

@jrgm did you want to adjust the regexes to look for both variants instead?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 278869195a0265fde778a433bd84802ca79f0d1c
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7efa1b96c374f87222b9ec70372ca483f6952071
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7efa1b96c374f87222b9ec70372ca483f6952071
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 33a04ed0bc8ae18213f5c9421d0f04ceae2dd37c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fa09c5518ae512be9a04ef1869fddad96dc7cc46
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: d7d91bc1e383806cc6ea3f1c3cd45b043a7d8ada
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
