### PR TITLE
feat(locale): enable Finnish locale

### LINKED ISSUE #3737: Add `fi` to enabled locales
100% on https://pontoon.mozilla.org/fi/firefox-accounts/

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3737

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

**Comment by vladikoff** [comment]
100% on https://pontoon.mozilla.org/fi/firefox-accounts/

**Comment by vbudhram** [comment]
LGTM!

screen shot 2016-05-13 at 11 35 42 am

**Comment by vladikoff** [comment]
woohoo!

**Pull request merged**
