### PR TITLE
fix(styles): fixes avatar styling to be consistent with fx desktop

### LINKED ISSUE #3276: Make the FxA avatar consistent with Firefox desktop
When in settings, keep the avatar borderless and copy the hover and down styles from desktop.

### PR DESCRIPTION
**Pull request by vbudhram**
fixes #3276

### CODE REVIEW

**Comment by zaach** [comment]
\o/

**Comment by rfk** [comment]
*\o/*

**Comment by vladikoff** [comment]
\o\

**Comment by zaach** [comment]
/o/

**Comment by rfk** [comment]
\o~

wait, what dance is this again?

**Pull request merged**
