### PR TITLE
chore(readme): update readme with grunt sass watch

### LINKED ISSUE #3876: Add `grunt sass watch` to readme grunt commands

### PR DESCRIPTION
**Pull request by TDA**
Fixes #3876

### CODE REVIEW

**Comment by vladikoff** [comment]
@larissagaulia please take a look. Thoughts on the new doc?

**Comment by larissagaulia** [comment]
Put it under grunt tasks is OK. But not sure it's gonna b clear for a new contributor that if they want to change a css file they need to run this watch and edit the .scss file so it's gonna be compiled to the corresponding css.

Maybe you could add an 'Editing stylesheets' h3 under [Development Setup](https://github.com/mozilla/fxa-content-server/blob/f75e317f11c6952a955e3a1c19d55f8ad49d557e/README.md#development-setup) and shortly explain "In order to change stylesheets make sure to run grunt sass watch and add your contribution under the proper .scss file".

**Comment by TDA** [comment]
@vladikoff @larissagaulia Added that, and while we are at it, should we also add a `Changes to scripts and templates` section? Just for the sake of completeness. (even though we dont have to do anything to reload those)?

**Comment by TDA** [comment]
@vladikoff whats the deal with Travis?

**Comment by vladikoff** [comment]
Thanks!

**Comment by larissagaulia** [comment]
@TDA, IMHO the more information we get out there, the better. people should feel confident about taking the first steps on their own, it's less frustrating for new contributors.

**Pull request merged**
