### PR TITLE
[PROPOASL] SSO: Support to prevent asking password again to already authenticated users on supported reliers

### PR DESCRIPTION
**Pull request by renoirb**
How about separate, trusted+supported,  web application could just "log you in" without asking your password more than once. a.k.a. SSO

The following patch would make FxA able to give an OAuth2 one time `code` string so a configured relier would be able to get an OAuth `Bearer` token.

Idea is that each relier could then use the token, ask a "source of truth" (i.e. `fxa-profile-server`), the relier could then make sure a user exists locally and start a session. This has to be done in two separate components. [An initializer JavaScript module](#An initializer JavaScript module), and [Set in place two HTTP handlers on web app relier](#Set in place two HTTP handlers on web app relier)

To see the idea in action, [see this video](http://www.youtube.com/watch?v=rutwd1Z_1TE) where you'll see two separate wikis, on different domains, ensures the session state is in sync with FxA.
 
[Synchronize session state accross separate web applications](http://www.youtube.com/watch?v=rutwd1Z_1TE)

## More notes about the feature

* [this comment](https://github.com/mozilla/fxa-content-server/issues/1386#issuecomment-51381907)

### OAuth server patch

ref: mozilla/fxa-oauth-server#279

### An initializer JavaScript module

Refer [to this this **gist**](https://gist.github.com/WebPlatformDocs/fe3149c60d6ed95c7e16)

### Set in place two HTTP handlers on web app relier

* Each web application has to be registered to the OAuth server as both: `{trusted: true, canSso: true}`
* Backend has to support reading from a  "source of truth" (i.e. `fxa-profile-server`)
  * If FxA has no session, ensure relier web app kills any session (done through [JavaScript initializer module](An initializer JavaScript module))
  * If FxA has session, it MUST match session it has locally
* Ensure possible user data changes are reflected on relier web application locally

#### PHP Backend strawaman

The following is planned to be factored out as a PHP module so that other systems would take care of the specifics the  [JavaScript initializer module](An initializer JavaScript module) would trigger via xhr HTTP calls from its iframe.

* [FirefoxAccountsManager class](https://github.com/webplatform/mediawiki-fxa-sso/compare/master...webplatform-sso#diff-df6204a5520d4e71eaa9ebfa75e6034eR1)
* [a very rough (clumsy) attempt to handle session based on data from profile server](https://github.com/webplatform/mediawiki-fxa-sso/blob/2eff4350d6f09445fa5a9b0ded43d170c43409b7/includes/WebPlatformAuthHooks.php#L241), the block at `if ( is_string( $state_key ) && is_string( $code ) ) { /* here */ }`

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 645d8bffcd6861b7c24847334e7dbb40f37e1886
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Thanks for sending this PR, working on this and showing a demo at Whistler! it was great!

 We are going to hold of on working this because no one requested SSO functionality. However we will keep this PR in mind.

**Comment by rfk** [comment]
Seconded, it was really great to see this come together at Whistler.

We can't justify merging this to mainline without a compelling use-case within the Firefox connected experience, but two notes:

* I'm really pleased to see that this was cleaner than the previous approach you took for SSO, that's a good sign of healthily evolving code
* I'd be happy to consider any refactorings that would make this easier to maintain in an ongoing fork

IIUC, the core of the experience here is just skipping the "signin" prompt entirely for a certain set of reliers.  I wonder if that could be useful more broadly than just the sso scope you outline here.  Worth thinking about.

**Comment by renoirb** [comment]
Thanks for the feedback.


I'm OK to not merge right away, i will find time to create relier module in
JavaScript, and create backend PHP and Python modules too. With that in a
usable state we could have concrete use cases

**Comment by groovecoder** [comment]
FWIW, we may need/want this for [MDN](http://developer.mozilla.org/)-[BrowserCompat](http://browsercompat.herokuapp.com/) SSO via Firefox Accounts.

**Comment by renoirb** [comment]
\0/

**Comment by renoirb** [comment]
I’ve described, once more, how it all works together in [Bugzilla 1050399 comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1050399#c10).

**Pull request closed without merging**
