### PR TITLE
chore(tests): Add missing test for base64url encoding.

### PR DESCRIPTION
**Pull request by rfk**
So I found this un-commited test file lying around in my checkout of fxa-content-server.  I suspect it was accidentally left behind from a previous PR.  Better late than never?

### CODE REVIEW

**Comment by rfk** [comment]
> Coverage remained the same

How disappointing...

**Comment by vladikoff** [comment]
@rfk You also need to include the test in`test_start.js`
image
image

**Comment by vladikoff** [comment]
To grep the test visit: 
`http://localhost:3030/tests/index.html?grep=lib%2Fbase64url`

**Comment by rfk** [comment]
*sigh* I step away from this repo for a month or two, and I completely forget how things work.  Thanks @vladikoff!

**Comment by rfk** [comment]
Fortunately it seems to have been a broken test, not broken code-we-already-commited.

**Comment by rfk** [comment]
> Coverage increased

That's more like it :-)

**Pull request merged**
