### PR TITLE
fix(password): display localized tips for choosing password

### PR DESCRIPTION
**Pull request by l-hedgehog**
The patch we're using on https://accounts.firefox.com.cn/, not quite sure where is the best place to introduce the translator.

### CODE REVIEW

**Comment by vladikoff** [comment]
not sure why you need this, we already have translator function above. maybe those are not working properly. I will check...

**Comment by l-hedgehog** [comment]
Hi @vladikoff, if you mean `BaseView.t`, I think it's just for extraction of localizable strings, instead of really localizing them.

**Comment by vladikoff** [comment]
> Hi @vladikoff, if you mean BaseView.t, I think it's just for extraction of localizable strings, instead of really localizing them.

Ah you are probably right. I'll check 👍

**Comment by vladikoff** [comment]
closed in favour of https://github.com/mozilla/fxa-content-server/pull/4068

**Comment by l-hedgehog** [comment]
Thanks!

**Pull request closed without merging**
