### PR TITLE
fix(settings): make header bottom margin uniform

### LINKED ISSUE #3131: Top padding in account picture section of settings should be 20px
Eagle eyed this one after a sleepless weekend wondering what was bothering me.

padding

### PR DESCRIPTION
**Pull request by johngruen**
Fixes #3131

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a2630c70a5372db2f0d2613ce2e9eff79b97a950
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
@johngruen - can you add a space between `fix(settings):` and `make` so that GitCop is happy?

**Comment by johngruen** [comment]
@shane-tomlinson done!

**Comment by shane-tomlinson** [comment]
screen shot 2015-10-12 at 16 42 55

Looks great @johngruen!

**Pull request merged**
