### PR TITLE
feat(SMS): Set France (FR) to 50%

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Please hold off on this one, I want to get confirmation from one more person.

**Comment by vladikoff** [comment]
@eoger Do you have a French SMS number to test this by any chance? https://github.com/mozilla/fxa-content-server/pull/5800/files 🇫🇷

**Comment by eoger** [comment]
Sorry not until 1 or 2 weeks my sim card is in the mail! 💌

**Comment by vladikoff** [comment]
> Sorry not until 1 or 2 weeks my sim card is in the mail! 💌

hah okay!

**Comment by vladikoff** [comment]
@natim says he got the SMS :) Thanks Remy!

**Pull request merged**
