### PR TITLE
chore(deps) update express-able

### PR DESCRIPTION
**Pull request by dannycoates**
For using experiment repo branches.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 525093c632e052772cbb41c04bde69e5e2862b0b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Hmm
```
fxa-content-server.route.500.ERROR: Error: Command failed: /bin/sh -c git clone -b master  /home/travis/build/mozilla/fxa-content-server/experiments
```

**Comment by vladikoff** [comment]
It seems to be working locally, checking...

**Comment by vladikoff** [comment]
Nvm had to delete the experiments directory now getting
```
 Error: Command failed: fatal: repository '/Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server/experiments' does not exist
```

The problem seems to be that the able node module is not fetching the right `github-url-to-object`, it is still the old version :(

**Comment by vladikoff** [comment]
fixed via https://github.com/mozilla/fxa-content-server/issues/2736

**Pull request merged**
