### PR TITLE
Issue 1992 boost router coverage

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@zaach - here is the follow on for #2133 to boost test coverage to router.js

### CODE REVIEW

**Comment by zaach** [comment]
The commit history looks strange here. #2133 was merged but the diff still shows changes related to FormPrefill. @shane-tomlinson should this be rebased?

**Comment by shane-tomlinson** [comment]
@zaach - ya, I'll do it in the morning, it'll be ready by time you come back online.

**Comment by shane-tomlinson** [comment]
@zaach - rebased.

**Comment by zaach** [comment]
:+1:

**Pull request merged**
