### PR TITLE
fix(signin-unblock): Fix Fx >= 57 screen transition after signin unblock.

### LINKED ISSUE #5488: Fx >= 57 transitions to the wrong screen after unblocking a Sync signin
Follow on from #5472.

Firefox >= 57 transitions to /settings instead of /signin_confirmed or /connect_another_device.

See https://github.com/mozilla/fxa-content-server/blob/f1f8a00cc61ca7efd1afb8b91746129b1f69a69a/tests/functional/sync_v3_sign_in.js#L202

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #5488

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57ad5cd7d5b1a8c9832af443ccf7c9ba3bca50e3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
Builds on #5546 and should be reviewed afterwards.

**Comment by vladikoff** [comment]
from mtg: for point release of train-97

**Comment by vladikoff** [comment]
Worked in my testing 👍

**Pull request merged**
