### PR TITLE
Layout issues in “Sign in” pop-up window of marketplace (bug 1204421)

### PR DESCRIPTION
**Pull request by atiqueahmedziad**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 546b27e1c3cb2a92dbacd00b87673da255bc8bf1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
cc @johngruen this is trying to fix this:
image

But might need a better solution

**Comment by vladikoff** [comment]
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1204421

**Comment by vladikoff** [comment]
r- on this PR, it totally breaks layout:

**Comment by vladikoff** [comment]
cc @rfk

**Comment by rfk** [comment]
Thanks for the PR @atiqueahmedziad, unfortunately it looks like it breaks layout on wider screens.  I'm going to surface this up as an issue for further discussion and close out the PR: https://github.com/mozilla/fxa-content-server/issues/3065

**Comment by johngruen** [comment]
Huh, weird issue. Must be something to do with the pop up since the layout should respond down to like 280px for trusted UI context. I'll fiddle with this tomorrow.

**Comment by vladikoff** [comment]
Thanks @johngruen !!

**Pull request closed without merging**
