### PR TITLE
Some small style fixes.

### PR DESCRIPTION
**Pull request by bwinton**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d96568771f53ea1ae5cb3b015faba8e9ec3d0399
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Hey @bwinton, 

I tested this in Chrome and it moved the grid into 2 cols: 




It's deployed to https://featurebox.dev.lcip.org/settings if anyone wants to test ( cc @ryanfeeley )

in iOS

**Comment by ryanfeeley** [comment]
@vladikoff Secondary email button missing style? 
image

**Comment by vladikoff** [comment]
@ryanfeeley where did u get that from?

**Comment by ryanfeeley** [comment]
@vladikoff i just clicked on [your link](https://featurebox.dev.lcip.org/settings) and was probably already signed in but in an email-unverified session. did my last PR to change that button do this possibly?

**Pull request closed without merging**
