### PR TITLE
Pass instanceId in OAuth views

### PR DESCRIPTION
**Pull request by eoger**
Connects to https://github.com/mozilla/fxa-auth-server/issues/2547

### CODE REVIEW

**Comment by eoger** [comment]
@shane-tomlinson It is not mandatory, as the server generates one for you.
However a well-behaved client should try to pass an instance ID on subsequent flows to avoid creating dupe client instances.
The way I see it, the FxA Client would generate an instance ID once, persist it and pass it every time it generates a flow URL.

**Comment by rfk** [comment]
Is this to help us move towards client-generated ids that align with the ecosystem metrics proposal, or would be still need it even if that weren't in play?  (I'm wondering how much this overlaps with the Incremental OAuth spec, which provides the existing refresh token at the end of the flow rather than providing an id at the start of the flow).

**Comment by rfk** [comment]
@eoger from our most recent discussions, do we still want this or will we do "fake incremental oauth" until we're ready for the real thing?

**Comment by rfk** [comment]
I'd like to defer this until we prove that we need it, in the interests of keeping API surface small.

> (e.g. after a password change so we end up with the same device)

I think we can have the password change/reset mark refresh tokens as "stale" rather than outright deleting them, and trigger the device to go back through the incremental auth flow.  But we'll have to try that out at some point and see...

**Comment by eoger** [comment]
There's very little chance we will pass `instanceIds` explicitly in the future, let's just close this.

**Pull request closed without merging**
