### PR TITLE
feat(client): update to fxa-js-client 0.1.30

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/mozilla/fxa-content-server/issues/2557

### CODE REVIEW

**Comment by vladikoff** [comment]
@zaach r?

**Comment by shane-tomlinson** [comment]
@vladikoff - Since https://github.com/mozilla/fxa-js-client/commit/8f5911df5ed398bbbf817f3607e1d2ca712d52b6 now throws if the `uri` is missing, should we log that [when the client is initialized](https://github.com/mozilla/fxa-content-server/blob/16417f187670f430b7261f8f69b23f303201944c/app/scripts/lib/fxa-client.js#L29) or is logging taken care of already by the 500 handler?

**Comment by shane-tomlinson** [comment]
@vladikoff - the error is logged:

> "error.unknown context.unknown namespace.Error: Firefox Accounts auth server endpoint or configuration object required."

I'm confused how this version of the fxa-js-client fixes #2557; does it just sidestep the problem by throwing if `uri` is undefined? When I first investigated this problem, the only way I could recreate 'undefined' in the request is to [set config.authServerUrl to the string 'undefined'](https://github.com/mozilla/fxa-js-client/issues/142#issuecomment-71185640).

My general confusion aside, r+ on bumping the version with all the latest goodness.

**Comment by vladikoff** [comment]
> I'm confused how this version of the fxa-js-client fixes #2557; does it just sidestep the problem by throwing if uri is undefined?

Yeah, I guess the plan is to see if we get any of those errors in Sentry.

**Comment by shane-tomlinson** [comment]
> Yeah, I guess the plan is to see if we get any of those errors in Sentry.

Cool. I'm going to merge and reopen #2557 until we prove to ourselves we have really fixed this.

**Pull request merged**
