### PR TITLE
chore(lint): Check space after Unary ops

### LINKED ISSUE #2690: lint: Space after "!" not enforced
Looking at a PR to server code:

image

We should have eslint or jscs catch this for us. @pdehaan @TDA ideas?

### PR DESCRIPTION
**Pull request by TDA**
Fixes #2690
Add rule to JSCS, not ESLint
@pdehaan 
@vladikoff 
PS: Apparently needs a rebase.
Edit: Rebased.

### CODE REVIEW

**Comment by pdehaan** [comment]
:+1: LGTM! Nice work!

r? @vladikoff

**Comment by vladikoff** [comment]
@TDA could you rebase against master, there is new code here: https://github.com/mozilla/fxa-content-server/commit/177747f218dc0af5790fbf10f78055c026394063#diff-fbc078c2167b03ff7db6cfe8349db379R46 that should get caught with `grunt lint` 

if not I will rebase manually in a few hours.

**Comment by TDA** [comment]
@vladikoff Sure thing! will do!

**Comment by TDA** [comment]
@vladikoff Its done. Should be green.

**Comment by vladikoff** [comment]
Excellent, and thanks for rebasing it!

**Pull request merged**
