### PR TITLE
SVG icons for Devices & Apps

### PR DESCRIPTION
**Pull request by shorlander**
Add icons for devices and services for #4049

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 322cf2bbc7ad4234c1756f42b57deddbf80482f2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
All these will need to be optimized for file size with something like https://jakearchibald.github.io/svgomg/ , https://github.com/svg/svgo or other tools

**Comment by ryanfeeley** [comment]
@rfk @davismtl Please implement the device icons provided by Horlander ASAP.

**Comment by rfk** [comment]
Nice, thanks @shorlander!

I've built on top of your commit to optimize the SVGs, and to use the base laptop/phone/tablet images to replace the existing bitmaps:

  https://github.com/mozilla/fxa-content-server/pull/4294

So I'm going to close out this PR in favour of that one, and we can follow up on using the OS-specific variants in #4049.

**Pull request closed without merging**
