### PR TITLE
fix(styles): adjust radius on show button

### LINKED ISSUE #5233: Fix show password border radius problem
I noticed that the Show Password has a different border radius than the parent text input.

border-radius

I was hoping to fix this myself, but was unable to do all the states (hover, focus, etc) in DevTools.

It looks like what is 2px should be 4px.

Anyone keen to try?

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #5233

### CODE REVIEW

**Comment by vladikoff** [comment]
@mozilla/fxa-devs r?

**Comment by vbudhram** [comment]
This looked good to me in all states except pressed. There seems to be a little more white around corners. @ryanfeeley Thoughts?

With 2px border
screen shot 2017-07-19 at 2 06 22 pm

With 4px border
screen shot 2017-07-19 at 2 05 24 pm

**Comment by ryanfeeley** [comment]
@vbudhram 
hoverboard

**Comment by ryanfeeley** [comment]
@vbudhram Keep at it. @2x resolution is your friend (if you have it).

**Pull request closed without merging**
