### PR TITLE
fxa(signin): displaying new message for already verified sign-in tokens

### PR DESCRIPTION
**Pull request by divyabiyani**
Test cases added as was discussed in #4173 .
Also,squashed the commits and put them together as per the guidelines.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 71afd92dcaf8dcca3037364e816f870c88a36e96
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
> @vbudhram fxa is not a valid type.
> Should I generate a new pull request with type fix?

You can change your commit message. For example you can use `--amend`: https://nathanhoad.net/git-amend-your-last-commit and https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend

You don't have to open new pull request.

**Comment by vbudhram** [comment]
@divyabiyani Heh, yea what @vladikoff said. You can also perform an interactive rebase and reword the commit, https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 71afd92dcaf8dcca3037364e816f870c88a36e96
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 71afd92dcaf8dcca3037364e816f870c88a36e96
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by divyabiyani** [comment]
@vbudhram I tried doing the rebase thing.
It shows that it has been fixed up but when I am seeing here the commit is still there.

**Pull request closed without merging**
