### PR TITLE
Merge train-114 into master

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@mozilla/fxa-devs - r?

### CODE REVIEW

**Comment by rfk** [comment]
Should this include a change to shrinkwrap?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef4516c1028b763eed0dd12acf01c6edec7df141
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
> Should this include a change to shrinkwrap?

Good catch, updated!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef4516c1028b763eed0dd12acf01c6edec7df141
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6c7506497cb306a9830ebb5f36d722ad84fd0ab2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef4516c1028b763eed0dd12acf01c6edec7df141
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0a310b278337b154173e8d9c8ec836cb0bbb680d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef4516c1028b763eed0dd12acf01c6edec7df141
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0a310b278337b154173e8d9c8ec836cb0bbb680d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef4516c1028b763eed0dd12acf01c6edec7df141
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0a310b278337b154173e8d9c8ec836cb0bbb680d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 342b98e6a5742bab4dec2c16a00be4b933a7c690
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef4516c1028b763eed0dd12acf01c6edec7df141
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0a310b278337b154173e8d9c8ec836cb0bbb680d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 342b98e6a5742bab4dec2c16a00be4b933a7c690
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f2071bb9b24c4d53b32ca302cbf14d81618dc42d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
