### PR TITLE
Added QR code dimensions

### PR DESCRIPTION
**Pull request by ryanfeeley**
Added QR code dimensions in HTML to reduce layout jank when opening section

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@ryanfeeley - the CSS for the container specifies a width and height of 228px. Also seems like we should set the dimensions in CSS, no?

screenshot 2018-12-21 at 19 53 28

**Comment by vbudhram** [comment]
@ryanfeeley I tried to reproduce this on master but didn't see any layout jank when opening the section? Is there something specific I should look for?

Also, per shane, we should probably have this match image container's size.

**Comment by vladikoff** [comment]
cc @ryanfeeley any ideas?

**Comment by ryanfeeley** [comment]
I thought it was the image, but looking at a screen capture frame-by-frame I can see that it's not the image, but that the contents of the section changes.

When you open the section (using **Enable…** button) before the QR code appears, the section looks like this for a split second.
untitled-1

Is this a bug @vbudhram ?

**Comment by vbudhram** [comment]
@ryanfeeley I think I would consider that a bug. That view is shown while we try to determine that verification status of the session. It seems that it might be better to show nothing at all, or maybe a loading indicator?

**Pull request closed without merging**
