### PR TITLE
fix(form): fixes form autofill for Firefox and paste for iOS

### LINKED ISSUE #593: Auto-filled password in 'create account' and 'sign-in' dialogs does not light up 'Submit' button
If the password is auto-filled in either the create account or sign in dialogs, a user action (clicking 'show' or adding and deleting a space, for example) is required before the 'Submit' button is enabled.

### LINKED ISSUE #2450: Pasted passwords do not enable the sign in button
When a user pastes a password into the password field to log in (at least on iOS), the sign in button does not become enabled the way it does when they are typed it, but it should.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2450
Fixes #593

### CODE REVIEW

**Comment by vladikoff** [comment]
zzzzz

**Comment by vladikoff** [comment]
@shane-tomlinson @zaach r?

**Comment by zaach** [comment]
:+1:

**Comment by vladikoff** [comment]
Thanks Zach!

**Comment by shane-tomlinson** [comment]
Do we need the `keyup` & `change` events still?

**Pull request merged**
