### PR TITLE
fix(avatars): error message does not overlap with the default avatar

### LINKED ISSUE #2528: Avatar w/ missing gravatar briefly overlaps the error message over the default gravatar
Found in https://accounts.firefox.com/ver.json (commit 612cf49eca19faaf9ab3684b46c7310e9c28e1c2)

```js
{
  version: "0.38.1",
  commit: "612cf49eca19faaf9ab3684b46c7310e9c28e1c2",
  l10n: "03c2fb619b",
  tosPp: "dcbc323819"
}
```

---

### Steps to reproduce:
1. Go to https://accounts.firefox.com/
2. Create a new account (using an email without an existing Gravatar image)
3. Go to https://accounts.firefox.com/settings/avatar/gravatar

### Actual results:
For a brief second, there is a slight 1px red line intersecting my default avatar image.
avatar
**Figure 1:** Animations!

untitled
**Figure 2:** Static!

### Expected results:
No overlap. Probably a non issue after we refactor the Settings UX and if we temporarily disable gravatar support.
Also, after watching the looping GIF above, there is an awful lot of shifting buttons and elements when you click a Gravatar button.

### PR DESCRIPTION
**Pull request by eoger**
Fixes #2528

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
ref #2770

**Comment by shane-tomlinson** [comment]
@eoger - if you remove the `margin-top` declaration, I'll give you an r+

Here's what it looks like w/o the `margin-top`:

screen shot 2015-07-16 at 17 38 44

A bit more balanced with the header on top.

**Comment by eoger** [comment]
Done, ready for merge!

**Comment by zaach** [comment]
:+1:

**Pull request merged**
