### PR TITLE
fix(style): center the forgot password label

### PR DESCRIPTION
**Pull request by farhan787**
@shane-tomlinson fixed the issue #6907

### CODE REVIEW

**Comment by philbooth** [comment]
Hey @farhan787, it's worth taking a moment to read the contribution guidelines for this repo, particularly the section "Git Commit Guidelines":

https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

We normally try to make sure our commit messages are useful standalone message for people reading the git log, without needing to go and lookup an issue on GitHub. In this case, something along the lines of:

```
fix(style): center the forgot password label
```

...would be more helpful.

**Comment by farhan787** [comment]
@philbooth  thanks for correcting me, I'm fixing it and in future I'll keep this in mind.

**Comment by farhan787** [comment]
@philbooth is it correct now ?

**Comment by shane-tomlinson** [comment]
@vbudhram - mind reviewing this to see if it matches your expectations?

**Comment by farhan787** [comment]
@vbudhram it's my pleasure 😊

**Comment by SorinaFlorean** [comment]
following the steps from #6907, we confirm that this is fixed on Train 133 - stage.

**Pull request merged**
