### PR TITLE
fix(metrics): ditch the non-useful performance flow events

### PR DESCRIPTION
**Pull request by philbooth**
Following on from @irrationalagent's sweet demo last night, this PR gets rid of the raw perf events we were emitting for [his analysis](https://github.com/mozilla/fxa-adhoc-analysis/blob/master/fxa_perf.ipynb) and retains four that seem to be strongishly correlated to user behaviour: `connectStart`, `domainLookupEnd`, `redirectEnd` and `requestStart`.

They're also tweaked slightly so that they appear as `flow.performance.auth.xxx` and `flow.performance.other.xxx`, rather than the uncategorised `flow.performance.raw.xxx` I had them as before (which, to be frank, was a hack to get them shipped quickly). This makes sense both from a coding standpoint and a logical one.

A happy side-effect of this will be a drastic reduction in the number of events we're processing in Redshift. Things have got a bit slow on that front since we added all these, I noticed.

Sample events from local dev:

```
{"event":"flow.performance.auth","flow_id":"722e5c4c98678d29129398907729ea4af4f1386fcb8b03c91cbec8da45f18c4c","flow_time":1167,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4877,"time":"2018-01-09T12:32:16.566Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0","v":1,"context":"web"}
{"event":"flow.performance.auth.server","flow_id":"722e5c4c98678d29129398907729ea4af4f1386fcb8b03c91cbec8da45f18c4c","flow_time":13,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4877,"time":"2018-01-09T12:32:15.412Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0","v":1,"context":"web"}
{"event":"flow.performance.auth.client","flow_id":"722e5c4c98678d29129398907729ea4af4f1386fcb8b03c91cbec8da45f18c4c","flow_time":172,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4877,"time":"2018-01-09T12:32:15.571Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0","v":1,"context":"web"}
{"event":"flow.performance.auth.connectStart","flow_id":"722e5c4c98678d29129398907729ea4af4f1386fcb8b03c91cbec8da45f18c4c","flow_time":1,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4877,"time":"2018-01-09T12:32:15.400Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0","v":1,"context":"web"}
{"event":"flow.performance.auth.domainLookupEnd","flow_id":"722e5c4c98678d29129398907729ea4af4f1386fcb8b03c91cbec8da45f18c4c","flow_time":1,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4877,"time":"2018-01-09T12:32:15.400Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0","v":1,"context":"web"}
{"event":"flow.performance.auth.requestStart","flow_id":"722e5c4c98678d29129398907729ea4af4f1386fcb8b03c91cbec8da45f18c4c","flow_time":22,"hostname":"Phils-MacBook-Pro.local","op":"flowEvent","pid":4877,"time":"2018-01-09T12:32:15.421Z","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0","v":1,"context":"web"}
```

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by irrationalagent** [comment]
after a conversation with @philbooth this makes sense to me. I'll take up making the graphs for these events

**Comment by vladikoff** [comment]
@philbooth needs rebase

**Comment by philbooth** [comment]
> @philbooth needs rebase

Eh?

**Comment by vladikoff** [comment]
@philbooth oh sorry, saw: 
screenshot-2018-1-10 5a563dd7b41d1 jpg jpeg image 774 x 168 pixels - scaled 69

But it was okay to squash

**Comment by philbooth** [comment]
Weird, I thought I fixed all the conflicts yesterday, I merged `master` in straight after your intern4 changes landed.

**Pull request merged**
