### PR TITLE
fix(icons): add screenshots svg

### LINKED ISSUE #6769: Add app icon for Screenshots
FxA users can login to Screenshots. We should add an app icon.

screen shot 2018-12-20 at 12 23 23 pm

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #6769 

screen shot 2019-01-02 at 10 11 18 am

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram we should match the size and colour with other icons

**Comment by vbudhram** [comment]
@vladikoff Updated!

screen shot 2019-01-02 at 10 45 33 am

**Comment by vladikoff** [comment]
@vbudhram Hm still looks a bit big, can we compare it with Notes and maybe the default circle icon we have? cc @ryanfeeley

**Comment by vbudhram** [comment]
@vladikoff Ah, I see the problem, the other service icons have some white space padding around them. Using the icon from https://design.firefox.com/icons/viewer/#screenshot doesn't and fills the entire space.

@ryanfeeley Is it possible to get a formatted version of this icon?

**Comment by ryanfeeley** [comment]
@vbudhram @vladikoff Looks fine to me, if we reduce the icon size it will be blurry (not pixel snapped). Merge it!

**Comment by vladikoff** [comment]
Sure!

**Pull request merged**
