### PR TITLE
fix(basket): URI-encode email address in basket server urls.

### LINKED ISSUE #2524: Basket/proxy mishandling email addresses with non-alphanum characters
STR

1. Sign up with foo+bar@example.com
2. Try to subscribe and unsubscribe, and watch network traffic in browser
3. /lookup-user appears unable to remember state of user
4. Instead sign up as `foo@example.com`. No more confusion. 

Haven't traced through whether its the proxy or basket itself that has the problem, but I think it may be in the proxy from what I have seen.

### PR DESCRIPTION
**Pull request by rfk**
Fixes #2524

### CODE REVIEW

**Comment by rfk** [comment]
@vladikoff r?

**Comment by vladikoff** [comment]
Looking at this...

**Comment by zaach** [comment]
LGTM

**Comment by vladikoff** [comment]
from irc: 

I mentioned that the test for this should be a unit test, we cannot possibly test everything with functional tests because they are a lot slower. So my suggestion is to add unit tests to the basket server and use the `+extra` only for the functional test.

**Comment by rfk** [comment]
> I mentioned that the test for this should be a unit test, we cannot possibly test
> everything with functional tests because they are a lot slower.

Good call, thanks @vladikoff.  I did briefly look for a unittest suite it would make sense to add this to, but I think the current factoring of basket-proxy makes that difficult.

The next steps for this code are to pull it out into its own repository, and work towards shipping it as an independent stack.  We should certainly add more unittests as part of that transition.

**Comment by rfk** [comment]
(I filed #2535 to capture next steps)

**Pull request merged**
