### PR TITLE
Train 106 merge

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 39d6cb65e42208a41c97f34cd78ea5129745c9bc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by philbooth** [comment]
I'm just going to call out that if this had been vanilla-merged rather tha rebased, future change logs would continue to include the `v1.106.1` tag.

Instead, now it will look like the fix was in train 107 next time we tag a release.

SAD FACE

**Comment by vladikoff** [comment]
>  this had been vanilla-merged rather than rebased

hm this was `Rebase and merged`, but i guess you are looking for a merge that creates a `Merge commit` ?

**Comment by philbooth** [comment]
Yep, just a bog-standard `git merge` so that the tag is an ancestor node of future tags in the tree.

**Comment by philbooth** [comment]
Never mind, fortunately `v1.106.2` came along to save the day! I've fixed the conflict and merged so the tree is sane again now.

**Comment by vladikoff** [comment]
yay!

**Pull request merged**
