### PR TITLE
feat(metrics): emit view, engage & submit events for CAD

### PR DESCRIPTION
**Pull request by philbooth**
Fixes mozilla/fxa-amplitude-send#50.

Ditches the `fxa_sms - view` Amplitude event in favour of three new events:

* `fxa_connect_device - view`
* `fxa_connect_device - engage`
* `fxa_connect_device - submit`

These new events are emitted from both the old CAD screen and the new SMS screen. An extra event property, `connect_device_flow`, is used to distinguish between the screens and can be used to distinguish between further variations in the future.

I also included another tiny little tweak to `lib/server/amplitude.js`, preferring a camelCased key for one of the properties to make dereferencing it more readable.

Example log lines showing the new events:

* `/connect_another_device`

  ```
  {"op":"amplitudeEvent","time":1521122118766,"device_id":"42d31696f62c4465be8fd4aa817f57d5","event_type":"fxa_connect_device - view","session_id":1521122118195,"event_properties":{"device_id":"42d31696f62c4465be8fd4aa817f57d5","connect_device_flow":"cad"},"user_properties":{"ua_browser":"Firefox","ua_version":"61","experiments":["q3form_changes_email_first"],"flow_id":"ca8d3a20ac9e3d3ad4e8a5875b7fc35ee0f386766bba5f8a17f5002f21503cfa"},"app_version":"107","language":"en","os_name":"Mac OS X","os_version":"10.11"}
  {"op":"amplitudeEvent","time":1521122118766,"device_id":"42d31696f62c4465be8fd4aa817f57d5","event_type":"fxa_connect_device - engage","session_id":1521122118195,"event_properties":{"device_id":"42d31696f62c4465be8fd4aa817f57d5","connect_device_flow":"cad"},"user_properties":{"ua_browser":"Firefox","ua_version":"61","experiments":["q3form_changes_email_first"],"flow_id":"ca8d3a20ac9e3d3ad4e8a5875b7fc35ee0f386766bba5f8a17f5002f21503cfa"},"app_version":"107","language":"en","os_name":"Mac OS X","os_version":"10.11"}
  ```

* `/sms`

  ```
  {"op":"amplitudeEvent","time":1521122643922,"device_id":"cca3bb5712ba4296999c8313960569fd","event_type":"fxa_connect_device - view","session_id":1521122643469,"event_properties":{"device_id":"cca3bb5712ba4296999c8313960569fd","connect_device_flow":"sms"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"preferences","experiments":["q3form_changes_email_first"],"flow_id":"bb4815492734de8bd09f4612cb144d6ed1ddd7c400259fd90e0a6cd8de6a72ee"},"app_version":"107","language":"en","os_name":"Mac OS X","os_version":"10.11"}
  {"op":"amplitudeEvent","time":1521122648147,"device_id":"cca3bb5712ba4296999c8313960569fd","event_type":"fxa_connect_device - engage","session_id":1521122643469,"event_properties":{"device_id":"cca3bb5712ba4296999c8313960569fd","connect_device_flow":"sms"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"preferences","experiments":["q3form_changes_email_first"],"flow_id":"bb4815492734de8bd09f4612cb144d6ed1ddd7c400259fd90e0a6cd8de6a72ee"},"app_version":"107","language":"en","os_name":"Mac OS X","os_version":"10.11"}
  {"op":"amplitudeEvent","time":1521122655433,"device_id":"cca3bb5712ba4296999c8313960569fd","event_type":"fxa_connect_device - submit","session_id":1521122643469,"event_properties":{"device_id":"cca3bb5712ba4296999c8313960569fd","connect_device_flow":"sms"},"user_properties":{"ua_browser":"Firefox","ua_version":"58","entrypoint":"preferences","experiments":["q3form_changes_email_first"],"flow_id":"bb4815492734de8bd09f4612cb144d6ed1ddd7c400259fd90e0a6cd8de6a72ee"},"app_version":"107","language":"en","os_name":"Mac OS X","os_version":"10.11"}
  ```

Note there is no `submit` event for the old CAD screen, because there is no form on that view.

Also note, I don't have the green light for these changes from @davismtl and @irrationalagent yet, so let's not merge them until we get that. I had the changes locally though, so figured it was still worth getting the review.

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by irrationalagent** [comment]
This makes sense to me, better than having them as separate events (saves $)

**Comment by irrationalagent** [comment]
@philbooth obviously not looking to have this added to this PR, but I'm wondering about the old CAD screen with the app store buttons - would there be a way to track specific clicks on one of these, perhaps passed as a property of the engage event?

**Comment by philbooth** [comment]
> obviously not looking to have this added to this PR, but I'm wondering about the old CAD screen with the app store buttons - would there be a way to track specific clicks on one of these, perhaps passed as a property of the engage event?

I thought this was going to be really simple, but none of the existing event data seems to have it. Opened #5987 to come back to it.

**Comment by philbooth** [comment]
[Sounds like](https://bugzilla.mozilla.org/show_bug.cgi?id=1409247#c45) this won't be happening until late April at the earliest, so I'm moving this back to `next`.

**Pull request merged**
