### PR TITLE
fix(css): Show password border radius problem

### LINKED ISSUE #5233: Fix show password border radius problem
I noticed that the Show Password has a different border radius than the parent text input.

border-radius

I was hoping to fix this myself, but was unable to do all the states (hover, focus, etc) in DevTools.

It looks like what is 2px should be 4px.

Anyone keen to try?

### PR DESCRIPTION
**Pull request by xevrem**
fixes #5233

### CODE REVIEW

**Comment by vbudhram** [comment]
@xevrem Thanks for PR!

After playing around with it, it looks like a 3px border on the `big` layout might appear to be perfect size. The 2px border created some extra whitespace around the edges.

In the `small` size, a 1px appeared to blend perfectly.

Your PR:
original

Using updated
3px on big screen:
3px-big

1px on small screen:
1px-small

@ryanfeeley does that look better?

Ex:
```css
    @include respond-to('big') {
      border-radius: 0 $some-variable-with3px $some-variable-with3px 0;

      height: 43px;
      line-height: 42px;

      html[dir='rtl'] & {
        border-radius: $some-variable-with3px 0 0 $some-variable-with3px;
      }
    }

    @include respond-to('small') {
      border-radius: 0 $some-variable-with1px $some-variable-with1px 0;;
      height: 38px;
      line-height: 38px;
    }
}
```

**Comment by xevrem** [comment]
Hrmmm... looking into it, and forcing a darker background on hover, has revealed a whitespace border issue. The background color is not occupying all of its intended real-estate. I think the culprit is a `right: 1px` adjustment... i'll fiddle with it till i can get it to behave

P.S. using FF-Dev v57 and vivaldi

**Comment by xevrem** [comment]
I think setting the border radii as you state (3px-big 1px-small) will work if we also set the right-adjustment to be `0.5px`. 

so `.show-password-label` should probably read more like the following:

```
.show-password-label {
    background-color: $content-background-color;
    color: $input-placeholder-color;
    cursor: pointer;
    font-size: $base-font;
    min-width: 55px;
    padding: 0 7px;
    position: absolute;
    text-align: center;
    top: 1px;
    // it is very easy to accidentally select the text when clicking
    -webkit-touch-callout: none;
    // user select not supported by autoprefixer
    // https://github.com/postcss/autoprefixer/issues/167
    -moz-user-select: none;
    -ms-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    z-index: 3;

    html[dir='ltr'] & {
      border-left: 1px solid $input-row-border-color;
      right: 0.5px;
    }

    html[dir='rtl'] & {
      border-right: 1px solid $input-row-border-color;
      left: 0.5px;
    }

    @include respond-to('big') {
      border-radius: 0 $big-border-inner-radius $big-border-inner-radius 0;
      height: 43px;
      line-height: 42px;

      html[dir='rtl'] & {
        border-radius: $big-border-inner-radius 0 0 $big-border-inner-radius;
      }
    }

    @include respond-to('small') {
      border-radius: 0 $small-border-inner-radius $small-border-inner-radius 0;
      height: 38px;
      line-height: 38px;
    }
  }
```

with `$small-border-inner-radius` set to `1px` and `$big-border-inner-radius` set to `3px`

Thoughts?

**Comment by xevrem** [comment]
OK... I've a better fix. By changing `.show-password-label` from an inlay to an overlay, it eliminates all issues altogether with borders and aliasing. See the gist below, updated commit to follow.

https://gist.github.com/xevrem/5dc95629551910895217df9c533b2663

**Comment by vbudhram** [comment]
@xevrem Awesome, this works much better.

@ryanfeeley if you approve I think this is good to go.

rtl
gifltr

**Comment by ryanfeeley** [comment]
@vbudhram Possible to do a screen capture with quicktime so capture retina resolution? Send me vidyo on slack if it won't post here.

**Comment by ryanfeeley** [comment]
@xevrem Thanks Erika! If design is in the details, and I believe it is, contributions like these really help.

**Comment by xevrem** [comment]
@ryanfeeley welcome! glad to be able to help :)

**Pull request merged**
