### PR TITLE
feat(email): add new email graphic, switch to SVG

### LINKED ISSUE #5105: Replace graphic_mail PNG with this SVG
Current: a140168a graphic_mail 2x

Proposed:
[sent-email.svg.zip](https://github.com/mozilla/fxa-content-server/files/1029890/sent-email.svg.zip)

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #5105 

@ryanfeeley please review spacing?

image

image

image

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
I like the look of this graphic! 

@vladikoff - Can you do quick screen captures of how this looks with `/confirm_signin` and when the "Open GMail" button is displayed?

**Comment by ryanfeeley** [comment]
@vladikoff Is is odd that the first two screenshot are wider than the full desktop screenshot? Or is it just that the font is smaller? BTW, a higher contrast SVG is en route.

**Comment by vladikoff** [comment]
>  Is is odd that the first two screenshot are wider than the full desktop screenshot?

That's the mobile view vs desktop view that we have

**Comment by shane-tomlinson** [comment]
@vladikoff  - is this new graphic used for all of signup, signin, password reset, and add a secondary device? My guess is yes since the modification was made to two templates. If so, @ryanfeeley, is that as it should be?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Good catch! Yes, it should replace the old envelope everywhere, and can inherit the pop (if it's not a performance issue)

**Comment by ryanfeeley** [comment]
@vladikoff I got the higher contract SVG on Friday as promised 2 weeks ago. Reopen?

**Comment by ryanfeeley** [comment]
@vladikoff Higher contrast SVG
[Artboard 10.svg.zip](https://github.com/mozilla/fxa-content-server/files/1085718/Artboard.10.svg.zip)

**Comment by vladikoff** [comment]
@ryanfeeley could you please adjust that svg so it has equal padding on the right and left , relative to the envelope 📧  ?

**Comment by ryanfeeley** [comment]
@vladikoff Should be 144px wide now with the envelope centered. 
[wider.svg.zip](https://github.com/mozilla/fxa-content-server/files/1159725/wider.svg.zip)

**Comment by vladikoff** [comment]
@ryanfeeley thank you so much

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bbc9b84b76251ed5a231cba7e9f0ba0df5160d07
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bbc9b84b76251ed5a231cba7e9f0ba0df5160d07
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9f1408e095029aa6eae70cedd144791008d3aa9a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Final version checked with @ryanfeeley 👍 

image

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bbc9b84b76251ed5a231cba7e9f0ba0df5160d07
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9f1408e095029aa6eae70cedd144791008d3aa9a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
