### PR TITLE
feat(keys): add support to provide scoped keys

### PR DESCRIPTION
**Pull request by vladikoff**
Connects to https://github.com/mozilla/fxa/issues/217

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 064db415ac8e055b78d2866c291a3d004d88c656
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 188f70e1912c535723026db43fb92bb03a6c670f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 64720e93daa44048b312fe22c2b36b80326f2b05
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bffe75c19c83178584c365a1f0aca4713d54c436
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c81c9b92a50ed70d7b00c76b2abd45207ad2fac5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 95f5ac879118f6abf11403d19688f7d69674d6dc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c8877b30b65cff9203de23e2499ed1b5ee730603
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9a816a0adcad74317283cd510d74efdf00dcaae6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 264bb442dc6437da25a66c9a9e0ee7d9b9cb2db1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b832745b6269f13c6bb12fdbed4fbc7be4811d94
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0c96ecf70df70c14224ab3fdddb8ccaeea74dbb6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f698ba628ccf4dd8a716d048e316e1877f780014
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: dd4c63b846273e89ab34db2b09476c9395d00d28
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1a938df3699f2fabbd331d6f0a9bf7f7826b4fa1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5295733d68b6dedb90e2a809631f70db942697aa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bc1d0c0b1276c849d19b9bb810afac1a09097c97
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 13794b5008bf0fc669d2ce9271897ca1aeb7a889
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9d4382480877ec613239989afc83a93db86d8546
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bc665e5ac19f8b4db9c184444aff24600fda7e92
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Continued in https://github.com/mozilla/fxa-content-server/pull/5398

**Pull request closed without merging**
