### PR TITLE
fix(devices): add 'last active' to formatted string

### LINKED ISSUE #3960: In device manager, preface "minutes/hours/days/weeks/months ago" with "Last active:"
In device manager we shouldpreface "minutes/hours/days/weeks/months ago" with "Last active:"

e.g. Last active: months ago

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3960

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson r?

**Comment by shane-tomlinson** [comment]
@vladikoff, @ryanfeeley - I'm not going to block, but as a user I would look at `Last active: days ago` and go `Well, how many days ago?`

**Comment by vladikoff** [comment]
> @vladikoff, @ryanfeeley - I'm not going to block, but as a user I would look at Last active: days ago and go Well, how many days ago?

hah yeah :)

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson We do need the number in there. Fennec has it. I regret that date compromise, but I was young and needed the money.

**Comment by shane-tomlinson** [comment]
> I regret that date compromise, but I was young and needed the money.

I laughed so much I can't even think of a response.

**Pull request merged**
