### PR TITLE
fix(tests): adjust oauth 123done tests for logout

### LINKED ISSUE #3721: Failing test oauth permissions for trusted reliers - signin without `prompt=consent`, then re-signin with `prompt=consent`
> ./node_modules/.bin/intern-runner config=tests/intern_functional_full fxaAuthRoot=https://api-accounts.stage.mozaws.net/v1 fxaContentRoot=https://accounts.stage.mozaws.net/ fxaOauthApp=https://123done-stage.dev.lcip.org/ fxaUntrustedOauthApp=https://321done-stage.dev.lcip.org/ fxaIframeOauthApp=https://123done-stage.dev.lcip.org/iframe fxaEmailRoot=http://restmail.net fxaProduction=true grep='signin without `prompt=consent`, then re-signin with `prompt=consent`'

```
× firefox on any platform - oauth permissions for trusted reliers - signin without `prompt=consent`, then re-signin with `prompt=consent` (32.44s)
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/5fe8ce91-cda5-403a-8e93-546ed73615e2/element/34/click] Element is not currently visible and so may not be interacted with
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'jbuckley-23775', ip: '10.242.29.161', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_92'
Driver info: driver.version: unknown
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:138:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1071:12>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.openFxaFromRp  <tests/functional/lib/helpers.js:486:8>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:1008:25>
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:543:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.signin without `prompt=consent`, then re-signin with `prompt=consent` [as test]  <tests/functional/oauth_permissions.js:415:10>
  at <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3721

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

This is a quick fix until this is fixed fully with https://github.com/mozilla/123done/issues/153

**Comment by vbudhram** [comment]
The modified test case passed for me, however, I get some failures on other oauth_permissions tests, possibly unrelated?

```
× firefox on any platform - oauth permissions for untrusted reliers - signin with new permission available b/c of new account information (30.011s)
CancelError: Timeout reached on firefox on any platform - oauth permissions for untrusted reliers - signin with new permission available b/c of new account information
```

**Comment by vladikoff** [comment]
That test also uses the log out behaviour so could be related.

**Comment by vladikoff** [comment]
We shall keep an eye on it

**Pull request merged**
