### PR TITLE
<style>(<fxa-client>): add client icon for send in device list

### LINKED ISSUE #7062: Add client icon for Send in device list
I noticed that there is no device icon for Send in the client list. Here is one!
[Send_Glyph.svg.zip](https://github.com/mozilla/fxa-content-server/files/2984139/Send_Glyph.svg.zip)

### PR DESCRIPTION
**Pull request by AlbionaHoti**
Hi, @lmorchard 
I added the changes from your guide - Can you review it please, and if you can give me a hint on how to test this part because I see there is the clients.mustache file - there is the 'isOAuthApp' part - but should I create in a different way a firefox account so that part of the code can be shown? Because I can only see the **isWebSession** for now and the **showMobileApps**

fixes #7062

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Hi @AlbionaHoti - the icon looks good to me, could you rebase this PR off of the current master so that we can merge?

Screenshot 2019-03-26 at 13 39 46

**Comment by AlbionaHoti** [comment]
@shane-tomlinson I think I did something wrong! 

I did git rebase master - there were some merge conflicts - then fixed them - then git rebase --continue

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson I think I did something wrong!
> I did git rebase master - there were some merge conflicts - then fixed them - then git rebase --continue

From the looks of it, there's a merge

**Comment by shane-tomlinson** [comment]
@AlbionaHoti I used `git cherry-pick` to open a new PR with your change: https://github.com/mozilla/fxa-content-server/pull/7103. Closing this PR here.

**Pull request closed without merging**
