### PR TITLE
fix(sentry): remove noise from referer header in sentry

### PR DESCRIPTION
**Pull request by vladikoff**
@shane-tomlinson r?

### CODE REVIEW

**Comment by vladikoff** [comment]
"referer" is spelled wrong, but that's what they use https://github.com/getsentry/raven-js/blob/4ab26092b527cee6385bb9ba02e221448c5e62c1/src/raven.js#L695  ¯\_(ツ)_/¯

**Comment by jrgm** [comment]
> "referer" is spelled wrong ...

Spelled incorrectly, but it is the correct header (a historical "oops!" that will never go away). https://tools.ietf.org/html/rfc7231#section-5.5.2 ;-)

**Comment by shane-tomlinson** [comment]
I have no problems merging this. Is there an open issue that outlines the problem this solves?

**Comment by vladikoff** [comment]
> I have no problems merging this. Is there an open issue that outlines the problem this solves?

A precaution to avoid storing sensitive data. If we are fixing up the `url`, we should also clean up the `referer` because that is strongly related to the `url`. i.e user can open a new tab that uses `url` as `referer`

**Pull request merged**
