### PR TITLE
feat(icons): Use optimized svg icons in device view

### PR DESCRIPTION
**Pull request by rfk**
Replaces the existing bitmaps with shiny new SVGs provided by @shorlander.  We can do a separate PR to use the windows/mac/linux-specific variants, since @philbooth suggested that this info may not be available to the front-end without a corresponding back-end change.

@ryanfeeley I'll get this up on a dev box for your r?

Connects to #4049

### CODE REVIEW

**Comment by rfk** [comment]
This is now running on my dev box at:

  https://rfkelly.dev.lcip.org/settings?forceDeviceList=1

But of course, you actually have to connect some devices to it in order to see the icons.  I'll see if I can grab a screenshot to confirm.

**Comment by rfk** [comment]
Here's what the three new icons look like for me: 
screen shot 2016-10-18 at 17 09 55

@ryanfeeley @shane-tomlinson r?

**Comment by ryanfeeley** [comment]
@rfk Hmmm… those icons look blurry to me, like they're positioned or scaled a sub-pixel off. Is this a dummy account? If so, msg me a login? (save me time)

**Comment by rfk** [comment]
@ryanfeeley says
"""
they are sized wrong
they should be 32x32 but are 30x30
PRO TIP: if you want to vertically center device names make the line height 32px too
no padding
"""

**Comment by shane-tomlinson** [comment]
These contain inline `style` elements which I believe CSP will currently block. We can add the sha of the style to the CSP rules and all will be allowed.

**Comment by rfk** [comment]
Now that @vladikoff is back, I might just quietly back away from this little foray into front-end UI work and let him pick it back up...if that sounds OK to you @vladikoff? 😁

**Comment by vladikoff** [comment]
Yeap!

**Comment by vladikoff** [comment]
Tested this will csp rules and still works 👍  the new icons are really great!

**Pull request merged**
