### PR TITLE
fix(change_password): Change password field specific error, fixes #4768

### LINKED ISSUE #4768: “Your new password must be different” error should be field-specific
Discovered during Sync Fest.

“Your new password must be different” error should be field-specific
https://irccloud.mozilla.com/file/5rmX6ADE/new-different.png

### PR DESCRIPTION
**Pull request by greg-wolff**
I've gone through a few commits of trying to fix the ["Your new password must be different" issue](https://github.com/mozilla/fxa-content-server/issues/4768), and am having trouble having the ValidationError pop up. Currently, if you enter the same password as your old password, the change will be made successfully. Commenting out the return statement in the error handler seems to trigger both the original error message and the new validation error.

image
image

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 384f9565b99134c685fa76cbde456f93a008e584
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9b21ea18576d59ccdeba49008518048738c5b82b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 337ed8ad13d595c394981cf20b4e3bf4066db935
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
cc @shane-tomlinson @seanmonstar this is one of Outreachy candidates ^

**Comment by shane-tomlinson** [comment]
Hi @greg-wolff - @seanmonstar is correct, I suggested the wrong place to put the `.fail`. I suggested it there because it's close to the call to `fxaClient.changePassword`. However, as Sean pointed out, swallowing the error means `displaySuccess` will be called afterwards.

I think moving the `.fail` to [after all of the `.then`s will work](https://github.com/mozilla/fxa-content-server/blob/d129a6b6c7b876006edf7753d44c028816cb70c3/app/scripts/views/settings/change_password.js#L56)

Be aware that another contributor [is attempting to fix this bug too](https://github.com/mozilla/fxa-content-server/pull/4799), we'll merge whichever is ready first.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 384f9565b99134c685fa76cbde456f93a008e584
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9b21ea18576d59ccdeba49008518048738c5b82b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 337ed8ad13d595c394981cf20b4e3bf4066db935
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 93679655706eb506f6c1d1c15c76e4c64b95755c
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 384f9565b99134c685fa76cbde456f93a008e584
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9b21ea18576d59ccdeba49008518048738c5b82b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 337ed8ad13d595c394981cf20b4e3bf4066db935
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by greg-wolff** [comment]
fixes #4768.

Moved around the `.fail` under the `.then`'s and everything works now!

**Comment by shane-tomlinson** [comment]
@greg-wolff - this looks good! Can you also add a unit test in https://github.com/mozilla/fxa-content-server/blob/397afaf9a1dc9164b6c27d7b7bb56600f5087651/app/tests/spec/views/settings/change_password.js? It'll probably be similar-ish to [the error test](https://github.com/mozilla/fxa-content-server/blob/397afaf9a1dc9164b6c27d7b7bb56600f5087651/app/tests/spec/views/settings/change_password.js#L196:L216), the biggest difference is that the type of error returned will need to be a `PASSWORDS_MUST_BE_DIFFERENT`, and the failure handler won't be needed [like this section](https://github.com/mozilla/fxa-content-server/blob/397afaf9a1dc9164b6c27d7b7bb56600f5087651/app/tests/spec/views/settings/change_password.js#L208), and instead of checking for [propagates the error](https://github.com/mozilla/fxa-content-server/blob/397afaf9a1dc9164b6c27d7b7bb56600f5087651/app/tests/spec/views/settings/change_password.js#L213), it'd check to ensure `showValidationError` was called.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 384f9565b99134c685fa76cbde456f93a008e584
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9b21ea18576d59ccdeba49008518048738c5b82b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 337ed8ad13d595c394981cf20b4e3bf4066db935
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Hey @greg-wolff, I just merged another pull request that fixed this issue with working tests. I looked here first before merging, and noticed that the CircleCI tests were failing. But don't worry, there are other issues that can be fixed! And thanks so much for jumping in.

**Pull request closed without merging**
