### PR TITLE
Remove openid folder and all files

### PR DESCRIPTION
**Pull request by Vimal-Raghubir**
#6149 was raised to remove the openid folder and all of its content.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 811ddd422b91c27a41667bede188d3b1a285cfbb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8bed2c48a76038f00576af4bf2fda5dd5fefdc9a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
@Vimal-Raghubir - can you rebase this off of the current master please?

**Comment by Vimal-Raghubir** [comment]
Could you kindly advise me which commands I would need to execute to make the suggested fix? Thank you.

**Comment by shane-tomlinson** [comment]
@Vimal-Raghubir - I'm not sure what your remote's are called, I'll use "origin" to mean mozilla/fxa-content-server and "Vimal-Reghubir" to mean yours.

> git pull origin --rebase
> git push -f Vimal-Reghubir master:master

In the future, it's considered best practice to create a separate feature branch from master whenever you do feature work. There are a bunch of advantages to doing so, the primary reason is that you can work on multiple features at once, each in their own branch, whereas if you do all work in master you have only one branch to work with. Many teams (ours included) loosely follow what's known as [git flow where we create feature branches](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), and once those are approved, they are merged into master.

**Comment by vladikoff** [comment]
@Vimal-Raghubir could you please rebase this pull request?

**Comment by shane-tomlinson** [comment]
Thank you @Vimal-Raghubir, this type of work is a big help to us! 

I opened PR #6357 which contains the two commits here and is based on master.

**Pull request closed without merging**
