### PR TITLE
Updated the avatar to the latest haired one

### PR DESCRIPTION
**Pull request by ryanfeeley**
Please test it out to make sure it works OK as I don’t have the content server running locally and SVG files are more complex than bitmaps.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a43f6a13d0f2b142b5fc5be6d0c1bfafcea2a48c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Thanks Ryan, will check this out

**Comment by vladikoff** [comment]
@ryanfeeley 

Result:

**Comment by vladikoff** [comment]
@ryanfeeley what should we do about this?

**Comment by ryanfeeley** [comment]
@bryanbell Any ideas?

**Comment by bryanbell** [comment]
Can I have a copy of the old asset? That way I can make you a drop in replacement.

**Comment by vladikoff** [comment]
@bryanbell this: https://github.com/mozilla/fxa-content-server/blob/master/app/images/default-profile.svg ?

**Comment by bryanbell** [comment]
Can you try this? http://cl.ly/140E0S2T0V1c

**Comment by vladikoff** [comment]
> Can you try this? http://cl.ly/140E0S2T0V1c

Merged optimized version in: 
https://github.com/mozilla/fxa-content-server/commit/327d67ded5ae1d738fbb1b5e4264038a2bed7c64

**Comment by ryanfeeley** [comment]
As much as I feel this icon doesn't represent many of us in the bald community, :+1:

**Comment by shane-tomlinson** [comment]
> As much as I feel this icon doesn't represent many of us in the bald community, :+1:

Hear hear!

**Pull request closed without merging**
