### PR TITLE
fix(settingView): All panels will be closed while navigating from a childview to settings. 

### LINKED ISSUE #3386: Settings screen panes do not close when Back button is pressed
From https://bugzilla.mozilla.org/show_bug.cgi?id=1238960

Reproduced with Firefox 44.0b8 (build ID 20160111185352) on Windows 10 64-bit, Windows 7 64-bit, Mac OS X 10.8.5 and Ubuntu 12.04 32-bit

STR
*prequisite: user has a Firefox account
1. Launch Firefox with clean profile.
2. Log in using a Firefox account.
3. Go to about:preferences#sync and click "manage Account"
4. On The Firefox accounts page, click "Change" at any option (i.e. Display name/Communication preferences)
5. Hit the Back button.

Expected Results
The pane (Display name/Communication preferences) is closed.

Actual results
The pane is not closed, even if the URL changes. The pane correctly closes when "Cancel" is clicked, so it should also close for the back button.

Additional notes:
Reproducing with latest Nightly (20160111030207), latest DevEdition (20160112004003) and Firefox 43.0.4 (20160105164030).
Not a recent regression, it reproduces on Firefox 36 also (https://accounts.firefox.com/settings)

### PR DESCRIPTION
**Pull request by vershwal**
Fixes #3386 
@vladikoff @shane-tomlinson Please review. 
If this works fine I'll write tests for the same if required.

### CODE REVIEW

**Comment by mutdmour** [comment]
hmm. this would close the panels but not clear the inputs. I am doing something similar with #5801 to fix #4982. Once I add tests and PR is approved and merged, you could trigger the same event 'close:panel' I created.

**Comment by vladikoff** [comment]
@vershwal could you please rebase and update this using the code from @mutdmour ?

**Comment by vershwal** [comment]
@vladikoff Yes. I am following #5821. I'll fix this.

**Comment by vladikoff** [comment]
Thank you @vershwal !

**Pull request merged**
