### PR TITLE
feat(tests): ansible+cloudformation for teamcity test stack

### PR DESCRIPTION
**Pull request by jrgm**
@vladikoff - r?

Read this https://github.com/mozilla/fxa-content-server/blob/97c2730ff36a26b76653c5cdb6a72a9d003804ff/tests/teamcity/ec2-deploy/README.md

### CODE REVIEW

**Comment by vladikoff** [comment]
This is awesome and has great documentation! once thing I'm not sure if this is suitable for this repo. should we just make an fxa-teamcity repo instead, how generic should this be? can other teams use this to deploy their own CI for their own project?

**Comment by jrgm** [comment]
> This is awesome and has great documentation! once thing I'm not sure if this is suitable for this repo. 

Yeah, I thought about putting it in a separate repo, but decided to not do that. Maybe at a later date, after whatever other changes need to be done here. 

> how generic should this be? can other teams use this to deploy their own CI for their own project?

I kept being in generic in mind, but some things are particular to our needs, most particularly using route53 for dev.lcip.org, and the SSL key management in the IAM and ELB.

Other teams can certainly re-use this by forking it, and adjusting it to suit their needs.

**Comment by shane-tomlinson** [comment]
> Yeah, I thought about putting it in a separate repo, but decided to not do that. Maybe at a later date, after whatever other changes need to be done here. 

@jrgm - are there particular changes you have in mind?

**Comment by jrgm** [comment]
> other changes need to be done here.

Some things are noted in Todo/Bugs, but not blocking.

Anyways, changed my mind and this probably should be a separate repo. I'll close this PR, and eventually set up that rep.

**Pull request closed without merging**
