### PR TITLE
fix(tests): close unclosed window in functional test

### PR DESCRIPTION
**Pull request by philbooth**
I found this while trawling through the tests looking for things that might be breaking my inter-tab tests in Travis. Don't know whether it will resolve that problem yet but it strikes me as something we should fix anyway.

@shane-tomlinson r?

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@philbooth - are there any other instances in that file where a 2nd tab/window is opened but not closed? I wonder if this happens elsewhere in the tests too.

**Comment by philbooth** [comment]
I *think* this is the only place. I grepped for occurrences of `newwindow` and matched them against occurrences of `closeCurrentWindow`, everywhere else seems to be okay.

**Comment by shane-tomlinson** [comment]
> I think this is the only place. I grepped for occurrences of newwindow and matched them against occurrences of closeCurrentWindow, everywhere else seems to be okay.

I wonder if there is a way to hook up a global `afterEach` like construct that ensures `newwindow` is always torn down. Not for this PR obviously.

**Comment by philbooth** [comment]
> I wonder if there is a way to hook up a global afterEach like construct that ensures newwindow is always torn down.

+1,000,000 to that. Will have a look into it while I'm waiting for Travis to do its thing. :)

**Comment by shane-tomlinson** [comment]
r+, merge when travis goes green. The initial test failure is https://github.com/mozilla/fxa-content-server/issues/3197.

**Pull request merged**
