### PR TITLE
fix(links): adjust mobile app links

### LINKED ISSUE #3692: Make mobile apps link directly to their respective stores
Currently on our account verification pages we offer links to our mobile apps, but they link to our mozilla.org product pages. According to Alex Davis we should remove this step and instead link directly to the respective stores.

App Store:

* https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=ios&creative=button&fallback=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fapple-store%2Fid989804926%3Fpt%3D373246%26ct%3Dadjust_tracker%26mt%3D8

Play Store:

* https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=android&creative=button

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3692

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

**Comment by vladikoff** [comment]
new android play store link automatically opens the play store if needed

**Comment by vbudhram** [comment]
Tested out a few scenarios with the links

- Verify on desktop, iOS link opens iTunes store website 
- Verify on desktop, Android link opens in Play store website
- Verify on Android, link opens Play store
- Verify on iOS (safari), link fails to open

Not sure why iOS link failed to open, but I tested on iOS simulator and on browserstack with localhost tunneling. Thoughts?

**Comment by vbudhram** [comment]
> Verify on iOS (safari), link fails to open

@vladikoff Retested using a physical iOS and link prompts to open in App Store.

r+

**Pull request merged**
