### PR TITLE
fix(styles): update to new Photon colours

### PR DESCRIPTION
**Pull request by ryanfeeley**

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@ryanfeeley - is this ready?

**Comment by vladikoff** [comment]
@shane-tomlinson UX team is looking at it via https://ux.dev.lcip.org

**Comment by ryanfeeley** [comment]
@vladikoff @shane-tomlinson Just committed more changes to this PR with @bwinton’s help. It now loads the node module for Photon colours, and has a version, so their changes don't immediately clobber our design.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 32aadfc42cf9ad213ca14bb82ddc4066964f804d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 32aadfc42cf9ad213ca14bb82ddc4066964f804d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
