### PR TITLE
refactor(metrics): Removed get-metrics-errors.js

### PR DESCRIPTION
**Pull request by hritvi**
I have removed the get-metrics-errors.js file as things were stopped to be sent there since 2015 #5970

### CODE REVIEW

**Comment by vladikoff** [comment]
@hritvi hey! you also need to remove this line: https://github.com/mozilla/fxa-content-server/blob/e0bd497f918659421bacf2f9545002a46c6ffecc/server/lib/routes.js#L47 

This way the file you deleted is not `required` anymore. 

Also start the server locally `npm start` and see if `npm run test-server` passes. You might have to remove this line to make tests pass: https://github.com/mozilla/fxa-content-server/blob/e0bd497f918659421bacf2f9545002a46c6ffecc/tests/server/routes.js#L48

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ff906d7b49380d82acdc2339d43fbe4464f01c8f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3908716e87d1554f901b43d5523c8ccd02b03c98
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by hritvi** [comment]
Hey @vladikoff. Please review this pull request! Thanks :)

**Comment by vladikoff** [comment]
@hritvi thank you!!

**Pull request merged**
