### PR TITLE
chore(dev): update to sync-exec to support node 0.12

### PR DESCRIPTION
**Pull request by vladikoff**
@shane-tomlinson @zaach r?

### CODE REVIEW

**Comment by vladikoff** [comment]
I think this is the only thing that is blocking support for node 0.12 for the content server

**Comment by shane-tomlinson** [comment]
@vladikoff - with v0.12.1, I keep seeing:

> Running: complete_sign_up with expired link and click resend
> Waiting for email at: http://127.0.0.1:9001/mail/signin0.6726309412624687
> Assertion failed: (end <= source_len), function SliceOnto, file ../src/smalloc.cc, line 280.

**Comment by shane-tomlinson** [comment]
I forgot to say, I have blown away my node_modules directory and re-installed using v0.12.1 too.

**Comment by shane-tomlinson** [comment]
node v0.10.25 is happy.

**Comment by vladikoff** [comment]
The smalloc issue is related to https://github.com/joyent/node/issues/9180 and should not be related to this PR.

**Comment by shane-tomlinson** [comment]
Thanks @vladikoff. Since this problem does not manifest in node v0.10.x, I'm happy to merge.

**Comment by vladikoff** [comment]
Thanks!

**Comment by pdehaan** [comment]
> @shane-tomlinson: _"node **v0.10.25** is happy."_



They just released [Node v0.10.38](http://blog.nodejs.org/2015/03/23/node-v0-10-38-maintenance/), bro!

**Pull request merged**
