### PR TITLE
fix(tests): use bower@1.6.5 in teamcity tests

### PR DESCRIPTION
**Pull request by jrgm**
@vladikoff - r?

### CODE REVIEW

**Comment by vladikoff** [comment]
@jrgm could we also update our package.json? https://github.com/mozilla/fxa-content-server/blob/master/package.json#L29

**Comment by jrgm** [comment]
> @jrgm could we also update our package.json? https://github.com/mozilla/fxa-content-server/blob/master/package.json#L29

Sure, but seems orthogonal to this PR.

**Comment by vladikoff** [comment]
> Sure, but seems orthogonal to this PR.

The build will not pass (circle tests will fail due to old bower in package.json)

**Comment by jrgm** [comment]
Yeah, that's "orthogonal". ;-)

**Comment by vladikoff** [comment]
Thank you @jrgm !!

**Pull request merged**
