### PR TITLE
feat(client): firstrun - notify the parent of important events.

### LINKED ISSUE #2704: firstrun flow - notify iframe parent on initial screen load, login, and verification.
The firstrun flow would like to respond on certain FxA events:

* initial screen load
* login
* verification

cc @jpetto 

ref #2101

### PR DESCRIPTION
**Pull request by shane-tomlinson**
* `loaded` after the first screen is drawn.
* `login` after the user has signed in
* `verification_complete` after a signup/password reset verification is complete.

fixes #2704
ref #2101

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@jpetto and @philbooth - tag, you are it!

@jpetto - these are the events you asked for. Can you verify they work for you?
@philbooth - You'll need some extra infrastructure to test this.

1. https://github.com/shane-tomlinson/firstrun-example/ 
  1. clone, npm install, then start that server
1. Create a new firefox profile and use [this user.js](https://pastebin.mozilla.org/8839711) file to override preferences (place this file into `/Library/Application Support/Firefox/profiles/<your_new_profile_directory>/user.js`)
1. Open http://127.0.0.1:8111
1. Open the dev tools console
1. Run through the three affected flows (sign in, sign up & verify, reset password & verify) & ake sure the new messages appear in the console.

**Comment by philbooth** [comment]
@shane-tomlinson

I've tried a couple of times but I only get this:

screen shot 2015-07-17 at 11 37 25

Clearly I'm not following your instructions correctly, but I'm not sure which bit(s) I'm getting wrong. Maybe we can take a look at it together when you're back in LDN?

**Comment by vladikoff** [comment]
@philbooth check the ` "allowed_parent_origins": ["http://127.0.0.1:8080"],` in your local.json of the content server, you might need to add that 8111 endpoint.

**Comment by shane-tomlinson** [comment]
Adding more context:
* This PR will *only* work with Fx 40, 41, 42, etc. That is Beta, Aurora, and Nightly today.

**Comment by jpetto** [comment]
@shane-tomlinson I believe I'm seeing all available events: `ping`, `resize`, `loaded`, `login`, and `verification_complete`.

Would it be possible to send events on the sign up form, both for successful and unsuccessful submissions?

**Comment by shane-tomlinson** [comment]
> Would it be possible to send events on the sign up form, both for successful and unsuccessful submissions?

I'm pretty sure we can make that work. How do you define a successful vs unsuccessful submission? How are users counted that create a new profile and must sign in (vs sign up)?

**Comment by jpetto** [comment]
I would say successful is filling out all the fields correctly and hitting submit, unsuccessful would be hitting submit with an invalid email, password, or age.

I *think* what we want to measure is how many users submit the form *and* verify their email address.

cmore may have more thoughts in [bug 1150231](https://bugzilla.mozilla.org/show_bug.cgi?id=1150231).

**Comment by shane-tomlinson** [comment]
Thanks @jpetto - in the interest of getting this PR merged, I will open a new issue for success. @ncalexan wants a similar feature for fennec, so there is good overlap here.

**Comment by philbooth** [comment]
@shane-tomlinson, how come there's no test for `broker.afterLoaded` / `_iframeCommands.LOADED` in `app/tests/spec/models/auth_brokers/first-run.js`?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson, how come there's no test for broker.afterLoaded / _iframeCommands.LOADED in app/tests/spec/models/auth_brokers/first-run.js?

Probably developer oversight. I'll add one.

**Comment by philbooth** [comment]
Cool, other than that it looks good. Sorry it took me so long to get this working / review it! :-/

**Pull request merged**
