### PR TITLE
refactor(gravatar): Remove gravatar

### LINKED ISSUE #4931: Report on validity of Gravatar
We have some metrics in place to measure Gravatar. To me it looks like it produces more errors and 404s than returns real Gravatars. Should we simplify our UI and remove Gravatar altogether? Please report back with a solid analysis of the data.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@ryanfeeley - here it is!

fixes #4931

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Putting this in the backlog until we determine whether it's needed.

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

**Comment by vladikoff** [comment]
@shane-tomlinson do we still need: 

```
      &#gravatar {
        background-image: image-url('glyph-gravatar-32.svg');
      }
``` 

in CSS and the glyph?

**Comment by vladikoff** [comment]
Do we still need the metrics in client-metrics.md?

`#### settings/avatar/gravatar`

**Comment by vladikoff** [comment]
Leftover test in profile-client.js:

```
describe('postAvatar', function () {
        it('post an avatar url', function () {
          server.respondWith('POST', PROFILE_URL + '/v1/avatar',
            [201, { 'Content-Type': 'application/json' }, '{}']);

          return client.postAvatar(token, 'https://secure.gravatar.com/deadbeef', true);
        });
      });
```

**Comment by vladikoff** [comment]
in `models/account.js`:

```
        it('post an avatar url', function () {
          var IMG_URL = 'https://secure.gravatar.com/deadbeef';
          sinon.stub(profileClient, 'postAvatar', function () {
            return p();
          });
```

**Comment by vladikoff** [comment]
In metrics errors:
`tags.context (settings.avatar.gravatar)': testValidTagValue('context', 'settings.avatar.gravatar'),`

**Pull request merged**
