### PR TITLE
fix(metrics): fix get-metrics-flow to use correct view event

### PR DESCRIPTION
**Pull request by irrationalagent**
This fixes https://github.com/mozilla/fxa-content-server/issues/6660 so that the new about:welcome/activity stream/new tab firstrun form views make it to amplitude. following @philbooth suggestion to open this against train-123 so we can do a point release

### CODE REVIEW

**Comment by philbooth** [comment]
@irrationalagent, just fyi I'm going to experiment with pushing my CI changes from #6663 to this branch to see if we can unblock you. If it doesn't work I'll revert.

**Comment by philbooth** [comment]
Nope, didn't work, reverting.

**Comment by philbooth** [comment]
Sigh, I pushed with `:` when I meant `+`, accidentally closed the PR.

@irrationalagent, I've reinstated your original branch but GitHub won't let me re-open the PR for some reason. If you can't do it either we'll need to open a fresh PR, sorry.

**Comment by irrationalagent** [comment]
this is now here https://github.com/mozilla/fxa-content-server/pull/6664

**Pull request closed without merging**
