### PR TITLE
feat(style): Use system fonts instead of Fira Sans

### LINKED ISSUE #6145: Use system fonts, remove Fira Sans
child of #6083

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Extraction from #6116
issue #6083
fixes #6145

### CODE REVIEW

**Comment by vladikoff** [comment]
Can we remove this?

image

**Comment by vladikoff** [comment]
Do we still need to rev the fonts dir here:

**Comment by vladikoff** [comment]
There could still be the `fontello` font though, might have to rev that. However we haven't changed that in so long, we can probably just let stay the same and manually bump it if we ever change that.

**Comment by shane-tomlinson** [comment]
> There could still be the fontello font though, might have to rev that. However we haven't changed that in so long, we can probably just let stay the same and manually bump it if we ever change that.

I removed it initially, and it was fontello that caused me to put that line back. I'd rather just leave it as is personally and let automation take care of bumping, mere-humans have a good track record for forgetting things.

The .gitignore line to `app/styles/fonts` we should be able to remove. Good call.

**Comment by shane-tomlinson** [comment]
WIP removed from this, ready for review! @vladikoff, mind an r?

**Comment by vladikoff** [comment]
@shane-tomlinson do you want to replace fontello font with SVG icons in the future (follow up issue?)

**Comment by vladikoff** [comment]
worked well in my testing 👍

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do you want to replace fontello font with SVG icons in the future (follow up issue?)

👍 Check it out: https://www.npmjs.com/package/fontello-svg

**Pull request merged**
