### PR TITLE
fix(client & server): TOS/PP back button remains after page refresh.

### LINKED ISSUE #2044: Refreshing on the ToS/PN pages breaks layout/back button
Noticed this while fixing #2037

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@zaach or @vladikoff - r?

* "back" buttons are still available after the user refreshes the a page.
* If a user clicks on an external link from the TOS/PP text and then hits the browser's back button, show the "back" button is available.

fixes #2044

If this merges after #2330, it will need to be rebased.

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson I'm having an issue with a blank `main-content` area. To reproduce: 
 http://localhost:3030/legal -> click terms and get to: http://localhost:3030/legal/terms -> REFRESH the page, change browser url to (navigate manually) http://localhost:3030/de/legal/terms

image

**Comment by shane-tomlinson** [comment]
@vladikoff - fixed.

**Comment by vladikoff** [comment]
@shane-tomlinson this might be for a different bug, but we do get a blank page on something like:
http://localhost:3030/de/legal
https://accounts.firefox.com/de/legal
Not sure if these pages should be used or not.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson this might be for a different bug, but we do get a blank page on something like:
http://localhost:3030/de/legal

@pdehaan found this in #1443

**Comment by vladikoff** [comment]
manually tested + ran the tests locally.

**Pull request merged**
