### PR TITLE
feat(styles): Add support for .woff2

### LINKED ISSUE #3814: Use .woff2 fonts to shrink file size
Right now the connect-fonts-firasans package contains .woff fonts. Using .woff2 variants should shave a couple of KB off for supporting browsers. This can't necessarily be fixed here, instead it has to be fixed in the font pack, but this is to track and give myself a kick in the pants.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #3814

This shaves 8KB off of the download!

screen shot 2016-06-15 at 17 20 55

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@TDA, @philbooth - mind reviewing?

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa-checkbox/pull/23

**Comment by TDA** [comment]
@shane-tomlinson Looks perfectly fine, works. I have left comments in the checkbox-repo, and if thats all right, then r+ for this :)

**Comment by philbooth** [comment]
👍

**Comment by shane-tomlinson** [comment]
Thanks @philbooth and @TDA - The fonts are subtly different and I have to make a couple small CSS changes with @ryanfeeley's help, or else he's going to beat me over the head with a stick.

**Comment by ryanfeeley** [comment]
:face

**Comment by ryanfeeley** [comment]
@shane-tomlinson What subtleties are introduced?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - if you look through the CSS, I made a change to the checkbox - the checkbox and text were out of vertical alignment by 1px.

**Comment by TDA** [comment]
Real question is, did rfeeley hit you over the head with a stick @shane-tomlinson  😆

**Comment by shane-tomlinson** [comment]
> Real question is, did rfeeley hit you over the head with a stick @shane-tomlinson 😆

He hasn't had a chance to yet. I'm sure he will at some point, I self-merged after fixing the problems I saw.

**Pull request merged**
