### PR TITLE
chore(lint): Remove the eslint complexity checks

### LINKED ISSUE #2789: Remove ESLint complexity check
... Because bumping this every time we add a simple `||` to a method is marginally ridiculous;

```
/*eslint complexity: [2, 26] */
```

Alternatively, I think @shane-tomlinson had some `_.merge()` workaround for this that let us use the default complexity.

### PR DESCRIPTION
**Pull request by pdehaan**
The **eslint-config-fxa** module was already updated, but this just finishes the cleanup.

Fixes #2789

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c188e31b4a6b0d7404672b50e32ffa0a6460fdb0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by pdehaan** [comment]
Well played, @GitCop. Well played.

**Comment by TDA** [comment]
Someone got gitcopped :P :D @pdehaan 
LGTM! We can get this merged once ci/travis turn green :)

**Comment by pdehaan** [comment]
[insert fail GIF]

Yeah, so... I failed Travis. What the what?

Error was:
```
Running "eslint:grunt" (eslint) task
Running "eslint:app" (eslint) task
app/scripts/lib/app-start.js
  398:36  error  Function 'anonymous' has a complexity of 8  complexity
app/scripts/lib/cropper.js
  32:2  error  Function 'Cropper' has a complexity of 12  complexity
app/scripts/lib/metrics.js
  73:2  error  Function 'Metrics' has a complexity of 27  complexity
app/scripts/lib/screen-info.js
  13:2  error  Function 'ScreenInfo' has a complexity of 8  complexity
app/scripts/router.js
  297:19  error  Function 'anonymous' has a complexity of 7  complexity
app/scripts/views/base.js
  87:17  error  Function 'anonymous' has a complexity of 10  complexity

✖ 6 problems (6 errors, 0 warnings)

Warning: Task "eslint:app" failed. Use --force to continue.
Aborted due to warnings.
Execution Time (2015-07-24 23:26:55 UTC)
loading tasks    2s  ▇▇▇▇▇▇▇▇ 17%
eslint:grunt   1.2s  ▇▇▇▇▇ 10%
eslint:app     8.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 73%
Total 11.9s
The command "grunt lint" exited with 3.
```

Not sure what's going on, but spotted this as I sat weeping under my desk:
```
├── eslint-config-fxa@1.7.0
```

That SHOULD be **eslint-config-fxa@1.8.1** per [package.json:77](https://github.com/mozilla/fxa-content-server/blob/issue-2789-de-eslint-complexity/package.json#L77)

So, it seems like we're having an issue where the node_modules are getting cached and not always running the specified versions from package.json for each run. That's, "concerning".

/cc @vladikoff

**Comment by pdehaan** [comment]
My guess is that I want to do [this, "Clearing Caches"](http://docs.travis-ci.com/user/caching/#Clearing-Caches), but I'm a bit trigger shy as I don't want to break things [further] on a Friday at 4:45pm.

**Pull request merged**
