### PR TITLE
feat(test): Add functional tests for the `sync-suggestion` URL.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Follow on from #4798 to add functional tests.

Also extract UA strings into a common location
so they can be shared.

issue #4605

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

**Comment by shane-tomlinson** [comment]
I broke the tests! Putting this back into "active"

**Comment by shane-tomlinson** [comment]
Fixed the borked tests, ready for review, @mozilla/fxa-devs - r?

**Comment by philbooth** [comment]
LGTM! r+

**Pull request merged**
