### PR TITLE
fix(l10n): copy pt_PT to pt in l10n

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/mozilla/fxa-content-server-l10n/issues/81

### CODE REVIEW

**Comment by vladikoff** [comment]
Fixes https://github.com/mozilla/fxa-content-server-l10n/issues/81

**Comment by vladikoff** [comment]
@shane-tomlinson r?

**Comment by shane-tomlinson** [comment]
@rfk and I had a discussion yesterday where he mentioned,this same work needs to be done on the auth-mailer. All of our copy from one locale to another shenanigans do. Is this true Ryan?

**Comment by rfk** [comment]
> this same work needs to be done on the auth-mailer. 
> All of our copy from one locale to another shenanigans do

I believe this is true, yes, since fxa-auth-mailer should be using the same set of locales.

More broadly, I think we should move these tasks directly into fxa-content-server-l10n so that they can be maintained in a single place, rather than doing it twice in two different repos.

**Pull request merged**
