### PR TITLE
Made Last lowercase

### LINKED ISSUE #4989: Make Last active lowercase
From our copywriter we can (at least for English) can consistently apply lowercase on the last-connected and device-current timestamp row.

### PR DESCRIPTION
**Pull request by ryanfeeley**
Made “Last” lowercase to match lowercase in other second lines like current device.

(@rfk stealth edit to ensure waffle linkage: Fixes #4989)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57c198067a186e447d180710100c8ce4c39e9bcb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by ryanfeeley** [comment]
https://github.com/mozilla/fxa-content-server/issues/4989

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57c198067a186e447d180710100c8ce4c39e9bcb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
The train-87 string deadline has passed, let's hold off on merging this until train-88.

**Comment by vladikoff** [comment]
There is a fix for this in PR: https://github.com/mozilla/fxa-content-server/pull/5058

**Pull request closed without merging**
