### PR TITLE
Fix config for test/teamcity/latest, and also add config for stable

### PR DESCRIPTION
**Pull request by jrgm**
@vladikoff, I left off `/v1` and I think that explains the problems. And also added config for stable and stable-ff18, although there's probably no point in running stable-ff18, but symettry, yo.

### CODE REVIEW

**Comment by jrgm** [comment]
Oh, one thing on the test server, the config script for latest has `DISPLAY=:10` which didn't use to be there. Is that really needed now? It could be set in tests/teamcity/latest if needed

**Comment by vladikoff** [comment]
I think that needs to be `DISPLAY=:1`

**Comment by jrgm** [comment]
I can add that but why does only latest need that?

**Comment by vladikoff** [comment]
If stage works without it then it is okay to remove it

**Pull request merged**
