### PR TITLE
feat(design): switch to new mozilla logo

### LINKED ISSUE #4656: Update to latest Moz://a logo
We should probably update the Mozilla logo in the upper-right corner to the new Moz://a logo

https://www.wired.com/2017/01/introducing-mozillas-new-logo-moza-get/

create_a_firefox_account_and_mozilla_phonebook

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #4656

@ryanfeeley r?
newlogo

### CODE REVIEW

**Comment by vladikoff** [comment]
image
image

**Comment by ryanfeeley** [comment]
Whoah, y’all are really chomping at the bit here. Are you using #929fac on hover and 50% of that on opacity? Give that a try. I'm not sure at which height the logo will "pixel snaps" (so that there edges around the box are solid, not anti-aliased).

**Comment by ryanfeeley** [comment]
@vladikoff Actually in terms of size, you can copy the size from the mozilla.org home page, which I noticed is not pixel-snapped. I'm going to assume the new logo is not even pixel-snappable.
facepalm

**Comment by vladikoff** [comment]
> @vladikoff Actually in terms of size, you can copy the size from the mozilla.org home page

okay!

**Comment by vladikoff** [comment]
```
[11:00:16]  <rfeeley>	love it
```

**Pull request merged**
