### PR TITLE
Train 63 fixes

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6a4fa9c9512063d7b982879473fee182793836b3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aa6f3b7630a1a37305e5e55e7c5fe7b803c4e60f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by jrgm** [comment]
Fixing nsp nagging seems out of scope for a point fix.

**Comment by jrgm** [comment]
Not wanting `2,505 additions, 3,359 deletions` to npm-shrinkwrap and a change in expressjs version for a point release, I prepared v0.63.2, which skips over v0.63.1 and pulls in just the api fix and dropping the one test, but adds mozlog@2.0.4 since we are crashing on that, and a couple of workarounds to get travis to work in 63.

@vladikoff - r? - https://github.com/mozilla/fxa-content-server/compare/v0.63.0...v0.63.2

Can't do a PR for that since it conflicts with the branch train-63. These changes are on branch https://github.com/mozilla/fxa-content-server/commits/train-63-alt which is branched form tag v0.63.2

**Comment by vladikoff** [comment]
@jrgm 👍

**Pull request merged**
