### PR TITLE
fix(permissions): remove line break on permissions page

### LINKED ISSUE #3833: Line break on permission screen
Spotted this on Latest when trying out the Pocket registration flow.
screenshot 2016-06-10 12 58 27

### PR DESCRIPTION
**Pull request by TDA**
Fixes #3833 
Converts the div into a span
@vladikoff 
@ryanfeeley 

### With value and label
screenshot 2016-06-10 11 25 28

### With only label
screenshot 2016-06-10 11 34 25

### CODE REVIEW

**Comment by vladikoff** [comment]
Not working in Chrome:

image

**Comment by ryanfeeley** [comment]
@TDA The second line should line up with the first line, like the bullet in a list.

**Comment by TDA** [comment]
@ryanfeeley Fixed that.
@vladikoff That is due to an issue with fxa-checkbox, I am filing a follow-up PR there. To be clear, the problem is in lines: https://github.com/mozilla/fxa-checkbox/blob/master/checkbox.js#L236-L237
That needs to be changed to:
```
var firstChild = this.element_.firstChild;
this.element_.insertBefore(tickContainer, firstChild);
this.element_.insertBefore(boxOutline, firstChild);
```

Lets get both merged, so that this issue can be closed.

**Comment by TDA** [comment]
@vladikoff Also, fixed the extra height issue in chrome as well.

**Comment by TDA** [comment]
@vladikoff Looks like this now:
screenshot 2016-06-21 10 34 00
screenshot 2016-06-21 10 34 20
screenshot 2016-06-21 10 35 30
screenshot 2016-06-21 10 36 23

**Comment by vladikoff** [comment]
This is what I see in Chrome currently: 

image

**Comment by vladikoff** [comment]
image

**Comment by vladikoff** [comment]
Travis failing due to NSP. Otherwise good.

**Comment by ryanfeeley** [comment]
👍

**Pull request merged**
