### PR TITLE
style(settings_buttons): drag-off state for buttons

### LINKED ISSUE #5255: Add drag-off state for buttons
All of our buttons have a hover state. We should apply the same state for when users click on a button, but drags off. This lets the user subtly know that the action will be performed, but which button to return their cursor to if they want to perform the action.

Example from Bootstrap: 
what-a-drag

OS X does not do this, but likely because they don't offer hover states for their buttons:
off-state-osx

### PR DESCRIPTION
**Pull request by hritvi**
fixes #5255. I have added the drag-off state for settings button.Please tell me if I have to do it for all the buttons. Thanks!

### CODE REVIEW

**Comment by hritvi** [comment]
@vladikoff can we please try to rebuild the circleci test because the tests are passing on my localhost and thus I am unable to figure out the reason for the failing of circleci tests.

**Comment by hritvi** [comment]
Any updates on this @vladikoff. Thanks

**Comment by vladikoff** [comment]
@hritvi Hey! I think the tests will pass if you rebase against the master branch. 

Read more about `The Rebase Option` here: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by vladikoff** [comment]
Tests were failing, I Pressed rebuild, we shall see how it goes.

**Comment by vladikoff** [comment]
@hritvi Thank you!

**Pull request merged**
