### PR TITLE
feat(ios): Add ability for FxiOS to hide links to /signup.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
@rfk - I'm opening a PR for this. ;)

### CODE REVIEW

**Comment by rfk** [comment]
Hah, I was just typing one up myself :-)

So, I'm not thrilled about any of this code, but it has the advantage of giving us a short-term option that's super easy to remove when we no longer need it.  I'll lean on your architectural guideance for what a better, `context`-driven solution might look like.

**Comment by shane-tomlinson** [comment]
@rfk - if you are after a quick hack for train 43, I'm r+ for this. Also check out #2868 for a solution that adds the FxiOSV1 auth broker. That PR takes a different approach, instead of hiding the signup link, it just doesn't show it in the first place. That PR also enforces the inability to go to the /signup page if the user lands there somehow.

**Comment by rfk** [comment]
@shane-tomlinson great!  Can you please have a chat with @jrgm tomorrow and decide which parts we're able to land when?  If we can get the ios-context support out this week as a patch on train-42, then I think it makes sense to go straight to something like #2868 for train-43, and forget this one ever happened :-)

**Comment by shane-tomlinson** [comment]
Closing since #2868 was merged.

**Pull request closed without merging**
