### PR TITLE
fix(sign_up): make error for AGE-REQUIRED field specific on sign up screen

### PR DESCRIPTION
**Pull request by greg-wolff**
A similar tidy-up to (#4768)

On the sign up screen, makes the AGE_REQUIRED error a field specific error.

### CODE REVIEW

**Comment by alisha17** [comment]
Hi,
Can I work in resolving this?

**Comment by shane-tomlinson** [comment]
> Hi,
> Can I work in resolving this?

Hi @alisha17 - this pull request is @greg-wolff's work to fix the issue already, you are probably better off choosing another issue from [this list](https://github.com/mozilla/fxa-content-server/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-bug).

Be aware that the following are already being worked on: #4768, #4684, #4683, #4605.

**Comment by shane-tomlinson** [comment]
@greg-wolff - I have not tested it, but this looks like the correct approach. Can you also add/update the unit test in https://github.com/mozilla/fxa-content-server/blob/397afaf9a1dc9164b6c27d7b7bb56600f5087651/app/tests/spec/views/sign_up.js#L693:L695?

To run the unit tests, start the server set and browse to http://127.0.0.1:3030/tests/index.html

**Comment by vladikoff** [comment]
Please reopen a new PR with the fix for this 👍

**Pull request closed without merging**
