### PR TITLE
refactor(icon-service-firefox-notes): replace firefox-notes icon

### PR DESCRIPTION
**Pull request by himanish-star**
fixes : #5805 

I have replaced the firefox-notes icon with the new one

### CODE REVIEW

**Comment by rfk** [comment]
Thanks @himanish-star!  Just letting you know that we've got two team members on PTO at the moment so we may be a little slower than usual in getting this reviewed and merged...

**Comment by himanish-star** [comment]
@rfk , ok . Thanks for replying :smiley:

**Comment by vbudhram** [comment]
@himanish-star Thanks for submitting! Once we fix https://github.com/mozilla/fxa-content-server/issues/5836 and get our tests passing, I will circle back to this.

**Comment by himanish-star** [comment]
> @himanish-star Thanks for submitting! Once we fix #5836 and get our tests passing, I will circle back to this.

Thanks @vbudhram

**Comment by vbudhram** [comment]
@himanish-star Thanks!

**Pull request merged**
