### PR TITLE
refactor(client): remove campaign param support, switch to utm_campaign

### LINKED ISSUE #2920: Discontinue support for `campaign` query parameter
As @vladikoff notes in https://github.com/mozilla/fxa-relier-client/issues/51#issuecomment-129479266, `campaign` was originally for the Growth team. They now specify the `utm_campaign` parameter. Should we discontinue support for `campaign` and support only one way to do things.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2920

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Awesome, I'm happy to review this!

**Comment by vladikoff** [comment]
> Awesome, I'm happy to review this!

Okay!

**Comment by shane-tomlinson** [comment]
If I do a grep on `campaign`, there are a few references left over:

```bash
➜  scripts git:(i2920) rgrep "campaign" .
./lib/metrics.js:    'campaign',
./lib/metrics.js:    'utm_campaign',
./lib/metrics.js:        utm_campaign: this._utmCampaign, //eslint-disable-line camelcase
./lib/metrics.js:     * @param {String} campaignId - marketing campaign id
./lib/metrics.js:    logMarketingImpression: function (campaignId, url) {
./lib/metrics.js:      campaignId = campaignId || UNKNOWN_CAMPAIGN_ID;
./lib/metrics.js:      if (! impressions[campaignId]) {
./lib/metrics.js:        impressions[campaignId] = {};
./lib/metrics.js:      impressions[campaignId][url] = {
./lib/metrics.js:        campaignId: campaignId,
./lib/metrics.js:     * @param {String} campaignId - marketing campaign id
./lib/metrics.js:    logMarketingClick: function (campaignId, url) {
./lib/metrics.js:      campaignId = campaignId || UNKNOWN_CAMPAIGN_ID;
./lib/metrics.js:      var impression = this.getMarketingImpression(campaignId, url);
./lib/metrics.js:    getMarketingImpression: function (campaignId, url) {
./lib/metrics.js:      return impressions[campaignId] && impressions[campaignId][url];
./lib/sentry.js:    'campaign',
./models/activity-event-metadata.js: *   - utmCampaign: marketing campaign identifier
./models/activity-event-metadata.js: *   - utmMedium: marketing campaign medium
./models/reliers/relier.js:    'campaign',
./models/reliers/relier.js:    utm_campaign: Vat.string().renameTo('utmCampaign'),
./templates/marketing_snippet_ios.mustache:        <a class="marketing-link marketing-link-ios" href="https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=ios&creative=button&fallback=https://itunes.apple.com/app/apple-store/id989804926?pt=373246&ct=adjust_tracker&mt=8" data-marketing-id="spring-2015-android-ios-sync"><img width="129" height="45" src="{{ appStoreImage }}" alt="{{#t}}Download Firefox for iOS!{{/t}}" /></a>
./templates/marketing_snippet_ios.mustache:        <a class="marketing-link marketing-link-android" href="https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=android&creative=button" data-marketing-id="spring-2015-android-ios-sync"><img width="129" height="45" src="{{ playStoreImage }}" alt="{{#t}}Download Firefox for Android.{{/t}}"></a>
./templates/marketing_snippet_ios.mustache:                <a class="marketing-link marketing-link-android" href="https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=android&creative=button" data-marketing-id="spring-2015-android-ios-sync"><img width="129" height="45" src="{{ playStoreImage }}" alt="{{#t}}Download Firefox for Android.{{/t}}"></a>
./templates/marketing_snippet_ios.mustache:                <a class="marketing-link marketing-link-ios" href="https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=ios&creative=button&fallback=https://itunes.apple.com/app/apple-store/id989804926?pt=373246&ct=adjust_tracker&mt=8" data-marketing-id="spring-2015-android-ios-sync"><img width="129" height="45" src="{{ appStoreImage }}" alt="{{#t}}Download Firefox for iOS!{{/t}}" /></a>
./views/settings/devices.js:  var FIREFOX_DOWNLOAD_LINK = 'https://www.mozilla.org/firefox/new/?utm_source=accounts.firefox.com&utm_medium=referral&utm_campaign=fxa-devices';
```

The ones of concern are `lib/metrics`, `lib/sentry`, and `models/relier/relier`.

I wonder if there are any resume tokens left out there that have `campaign` instead of `utm_campaign`, if there are, will that cause a blowup when those users open the verification page? If `campaign` exists in the ResumeToken, but not `utm_campaign`, we should either convert or just silently ignore that field.

Otherwise, looks good.

**Comment by vladikoff** [comment]
> will that cause a blowup when those users open the verification page?

Does not seem to be the case, I tested with something like `http://127.0.0.1:3030/signup?campaign=vlad2333&entrypoint=linux` and resume token only got allowed values:

image

**Comment by shane-tomlinson** [comment]
Assigning back to @vladikoff to rebase.

**Comment by vladikoff** [comment]
cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
@vladikoff - I'll start running the tests as soon as the current batch of functional tests finish on my machine.

**Pull request merged**
