### PR TITLE
fix(input): remove autocapitalize on iOS

### LINKED ISSUE #2991: First character of password entry is capitalized on iOS
I have unconfirmed reports that when `context=fx_ios_v1` the first letter of the password input entry is automatically capitalized.  I believe that's controlled by the web content and not the embedding `WKWebView`.  Could I get confirmation and a fix, if it is in the content server?

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2991

### CODE REVIEW

**Comment by vladikoff** [comment]
### Before



### After

**Comment by rfk** [comment]
This LGTM, let's make sure we get it out on this train; r+

**Comment by rfk** [comment]
(but I'm not merging it just in case there's additional context or WIP that I'm not abreat of)

**Comment by vladikoff** [comment]
Thanks Ryan
!

**Pull request merged**
