### PR TITLE
fixes #7006

### LINKED ISSUE #7006: Local failing unit test: views/sign_up - render - positions password help tooltip on the second password field
> AssertionError: expected '' to equal 'auto'

I expect this is caused by a similar problem to https://github.com/mozilla/fxa-content-server/issues/6900

### PR DESCRIPTION
**Pull request by farhan787**
@shane-tomlinson now this issue is fixed. See, fxa-content-server/app/scripts/views/mixins/password-mixin.js file on line number 224 for this.

### CODE REVIEW

**Comment by SorinaFlorean** [comment]
@shane-tomlinson can you give us details on how to verify this issue? I've looked also at #7006 and pay attention to sign up page and the second password field on both stage and production and didn't see any major change. Thanks!

**Comment by farhan787** [comment]
@SorinaFlorean you've to first signin and then change your password and after your password has changed just look at the change password field again and the forgot password is aligned now after the fix.

**Comment by SorinaFlorean** [comment]
Thanks, @farhan787. Verified as fixed on stage - Train 132 following your steps.

**Comment by farhan787** [comment]
> Thanks, @farhan787. Verified as fixed on stage - Train 132 following your steps.

@SorinaFlorean your most welcome :-)

**Pull request merged**
