### PR TITLE
feat(connect-another-device): Add a close button to "why connect another device"

### LINKED ISSUE #4604: Add a close button to "Why Sync two or more devices"
@ryanfeeley asks for a big blue button that says "Got it"

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #4604

@ryanfeeley - it looks like this:

screen shot 2017-01-16 at 15 23 04

@ryanfeeley, @vbudhram - r?

### CODE REVIEW

**Comment by vbudhram** [comment]
@shane-tomlinson I couldn't get this view loaded to access the link when confirming account in FF or Chrome. I get the old view?

screen shot 2017-01-17 at 10 50 11 am

Am I missing something in the testing steps?

**Comment by vladikoff** [comment]
@shane-tomlinson we might want to add the "Got it" to the Device Disconnect as well (for consistency?)

**Comment by vladikoff** [comment]
@vbudhram try forcing the experiment into treatment mode: https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/connect_another_device.js#L103

**Comment by vbudhram** [comment]
@vladikoff yup that did it!

**Pull request merged**
