### PR TITLE
fix(sign_in_unblock):added a new case to onSignInError in app/scripts/views/sign_in_unblock.js

### PR DESCRIPTION
**Pull request by apoorvasingh17**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9e749da9e1f5ab4e1714640290515a91851b3ab
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: fee697eaf329537d55dd3a112d673eb0bdc31fa5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters

 * Commit: e611cb1a2df3a876ad2af14e98a516a16367dae4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f2827140e61088fb2932e7612347cec08c9f2695
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4f4fcaba019bb7c5fc5a5823617c02d3f3131cd8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters

 * Commit: 2ea96758c19943b188f5fe395979fa638604373a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b9a4b1510ce449712a3b4ba9223422787a23dc77
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: cad905dd7e1ac39409470c55230ce2dd4d0876c2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7cecd16218c6978c93d1aca6ce954fa597000104
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by apoorvasingh17** [comment]
@shane-tomlinson pls guide me further on how to proceed after adding the case.

**Comment by shane-tomlinson** [comment]
Hi @apoorvasingh17 - it looks like you created this pull request on top of your old pull request. 
Each pull request should live in isolation as much as possible, based on the newest possible code.

Second, pull requests are generally created against what is known as a "feature branch" instead of the "master" branch. "master" is a special branch that means "this is the most recent code that everyone should share."

If you are new to git, a great resource is the site [Think like a git](http://think-like-a-git.net/).

Here is what you should do to get started:

1. Rename your "master" branch to something else.
2. Pull the most recent code from origin.
3. Create a new master branch, based on "origin/master"
4. Create a new feature branch, based on your local "master".
5. Add your changes to the new feature branch.
6. Check in the new feature branch.
7. Push the new feature branch to your github fork.
8. Open a pull request.

What that looks like in bash:

1. `git branch -m master-old`
2. `get fetch origin`
3. `git checkout -b master origin/master`
4. `git checkout -b issue-5186-unblock-code-error`
5. do your edits.
6. `git add <files your modified> && git commit` - edit and save the commit message.
7. `git push <name of your github fork> issue-5186-unblock-code-error:issue-5186-unblock-code-error`
8. Open the pull request.

From [this question](https://github.com/mozilla/fxa-content-server/issues/5186#issuecomment-323392075):

> @shane-tomlinson Can you please highlight the part of the code where test needs to added?

Look here: https://github.com/mozilla/fxa-content-server/blob/9bc4821e0945d2dbf9a20c5bdae6a3533dd89568/app/tests/spec/views/sign_in_unblock.js

**Comment by apoorvasingh17** [comment]
@shane-tomlinson Can you please guide me more regarding the test?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Can you please guide me more regarding the test?

So that I can better guide you (I don't want to tell you to do things you've already done), can you tell me what you have tried?

**Pull request closed without merging**
