### PR TITLE
feat(client): Add support for `prompt=consent` for OAuth reliers.

### LINKED ISSUE #3505: Implement prompt=consent and scope restriction support in fxa-content-server.
Ref https://github.com/mozilla/fxa/tree/master/features/FxA-71-AMO-migration-support

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #3505

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Functional tests for the various cases are needed before merge.

**Comment by shane-tomlinson** [comment]
Functional tests added, I'm calling this one ready too.

**Comment by vladikoff** [comment]
Style issue with the template:

image

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 24e09608cc33d4413da55dd6a7646121fcb1fe1c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
