### PR TITLE
fix(metrics): Only send navigationTiming data on the first flush. 

### LINKED ISSUE #4601: navigationTiming data sent on every flush
STR

1. Visit http://127.0.0.1:3030/signup
2. Cause a blur event so the metrics are flushed.
3. Look at the content server logs for navigationTiming data.
4. Go back to the tab from step 1, click "Have an account? Sign in".
5. Cause a metrics flush.
6. Look at the content server logs for navigationTiming data. It's the SAME DATA!

### 1st flush:

```
{"time":"2017-01-10T11:00:00.000Z","op":"client.metrics","hostname":"stomlinson-30887","pid":41281,"v":1,"lang":"en","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0","duration":3753,"context":"web","broker":"base","entrypoint":"none","service":"none","migration":"none","nt.navigationStart":0,"nt.fetchStart":17,"nt.domainLookupStart":17,"nt.domainLookupEnd":17,"nt.connectStart":17,"nt.connectEnd":17,"nt.requestStart":17,"nt.responseStart":40,"nt.responseEnd":40,"nt.domLoading":40,"nt.domInteractive":116,"nt.domContentLoadedEventStart":123,"nt.domContentLoadedEventEnd":123,"nt.domComplete":138,"nt.loadEventStart":138,"nt.loadEventEnd":138,"events":["experiment.control.mailcheck.enrolled","signup.sync-suggest.visible","signup.email-optin.visible.true","flow.begin","screen.signup","signup.experiment.pw_strength.enabled","loaded"],"event_durations":[715,724,728,735,750,751,761],"screen.width":1680,"screen.height":1050}
```

### 2nd flush:
```
3|content- | {"time":"2017-01-10T11:00:00.000Z","op":"client.metrics","hostname":"stomlinson-30887","pid":41281,"v":1,"lang":"en","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0","duration":90675,"context":"web","broker":"base","entrypoint":"none","service":"none","migration":"none","nt.navigationStart":0,"nt.fetchStart":17,"nt.domainLookupStart":17,"nt.domainLookupEnd":17,"nt.connectStart":17,"nt.connectEnd":17,"nt.requestStart":17,"nt.responseStart":40,"nt.responseEnd":40,"nt.domLoading":40,"nt.domInteractive":116,"nt.domContentLoadedEventStart":123,"nt.domContentLoadedEventEnd":123,"nt.domComplete":138,"nt.loadEventStart":138,"nt.loadEventEnd":138,"events":["flow.signup.have-account","signin.ask-password.shown.account-unknown","screen.signin","signin.profile_image_not_shown"],"event_durations":[89742,89766,89779,89785],"screen.width":1680,"screen.height":1050}
```

This is busted because it causes us to report the same data to Statsd twice, skewing metrics. Users who flush N times will be represented in the performance data N times instead of once.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #4601 

Builds on https://github.com/mozilla/fxa-content-server/pull/4602 and should be reviewed afterwards.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Failing unit test, need to update.

**Comment by shane-tomlinson** [comment]
> Failing unit test, need to update.

Updated - @vladikoff, over to you.

**Comment by vladikoff** [comment]
Tested this and worked well in my tests!

**Comment by vladikoff** [comment]
Rebased this.., waiting for them CI

**Pull request merged**
