### PR TITLE
fix(config): switch to .com scopes

### PR DESCRIPTION
**Pull request by vladikoff**
@rfk r?

### CODE REVIEW

**Comment by vladikoff** [comment]
@rfk Ah I guess it makes sense to change all of those in tests

**Comment by rfk** [comment]
> I guess it makes sense to change all of those in tests

Yeah, agreed.  Sorry I missed this inconsistency earlier :-(

**Comment by vladikoff** [comment]
@rfk it's ok, also my fault

**Comment by vladikoff** [comment]
@rfk updated , gonna wait for CI

**Pull request merged**
