### PR TITLE
Add non-breaking space between mistyped and number

### PR DESCRIPTION
**Pull request by ryanfeeley**
To avoid a line break on a two word link, I have replace the space in Mistyped number? with a non-breaking unicode space. We should probably be doing this more often in other places to avoid "typographic orphans".

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d40e751c4a51292131e0a749630f2e0a5bf8021b
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
> To avoid a line break on a two word link, I have replace the space in Mistyped number? with a non-breaking unicode space. We should probably be doing this more often in other places to avoid "typographic orphans".

That string already uses HTML, so you should be able to use an `&nbsp;` character, which will come through to the translators more clearly why the update was made.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d40e751c4a51292131e0a749630f2e0a5bf8021b
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 002250a657b73749ec588c1eb2423ce26efc910c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d40e751c4a51292131e0a749630f2e0a5bf8021b
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 002250a657b73749ec588c1eb2423ce26efc910c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
