### PR TITLE
fix(icons): fixes 404s for iOS icons

### LINKED ISSUE #2062: 404s on /apple-touch-icon-*.png
Looking through the Kibana logs, I noticed that we have a few 404s for some apple icons:

- "GET /apple-touch-icon-120x120-precomposed.png HTTP/1.1"
- "GET /apple-touch-icon-120x120.png HTTP/1.1",
- "GET /apple-touch-icon.png HTTP/1.1",
- "GET /apple-touch-icon-precomposed.png HTTP/1.1",

Not sure if these are worth addressing, but I hates me some 404s as it clouds up our logs and makes it difficult to pull out legit 404s...

After a bit of Googling, I found these interesting links:
- https://mathiasbynens.be/notes/touch-icons
- https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

/cc @johngruen @ryanfeeley

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2062.

@pdehaan @zaach @shane-tomlinson r?

### CODE REVIEW

**Comment by vladikoff** [comment]
This fixes the 3 types of iOS 404s that we are getting in the logs. The sized versions are served to specific devices, the default icon is used as a fallback.

**Comment by pdehaan** [comment]
:+1:

@shane-tomlinson @zaach @johngruen: Any of you want to review before we press the big, shiny green button?

**Comment by zaach** [comment]
LGTM.

**Comment by pdehaan** [comment]
Alright, @zaach signs off on it, so we can blame him if it goes sideways. Merging!
Thanks @vladikoff!

**Pull request merged**
