### PR TITLE
fix(avatars): fix camera aspect ratio distortion

### LINKED ISSUE #1931: Avatar picture is distorted for 1920x1080 camera
@zaach i look even weirder than i usually do.

screen shot 2014-11-24 at 10 45 29 am

### PR DESCRIPTION
**Pull request by zaach**
@johngruen Could you try this patch out on your fancy webcam and see if it looks right?

Fixes #1931.

### CODE REVIEW

**Comment by zaach** [comment]
yeah yeah, ci error.

**Comment by vladikoff** [comment]
ping @johngruen

**Comment by johngruen** [comment]
@zaach hmmm...
screen shot 2015-08-03 at 10 34 11 am

**Comment by zaach** [comment]
@johngruen Are you sure that's not just how you look

**Comment by zaach** [comment]
@johngruen alright, for real this time it should work. Could you try again?

**Comment by zaach** [comment]
John and I tried to debug this over irc but the results were inconclusive. It seemed to work on Chrome but Firefox was still skewed.

**Comment by pdehaan** [comment]
@johngruen What's the make/model of your webcam?

**Comment by vladikoff** [comment]
closing this and moving discussion back to the issue

**Pull request closed without merging**
