### PR TITLE
fix(travis): test on node 4 and 6

### PR DESCRIPTION
**Pull request by jrgm**
fix(travis): test on node 4 and 6

r? - @shane-tomlinson

### CODE REVIEW

**Comment by jrgm** [comment]
So, this doesn't build since the tests assume that modules can be loaded from the npm@2 style layout of `node_modules`, e.g., `./node_modules/intern/node_modules/dojo/has.js`, and node6 ships with npm@3 which has a flatter `node_modules` layout. 

So, this raises the question of how we intend to transition to node@6 and npm@3.

**Comment by pdehaan** [comment]
Why not just make **dojo** a devDep and `require('dojo/has')` directly?

**Comment by jrgm** [comment]
Why was this assigned to me?

**Comment by shane-tomlinson** [comment]
> Why was this assigned to me?

Because the tests fail. ;)

**Pull request merged**
