### PR TITLE
feat(connect-device): allow showSuccessMessage search param

### PR DESCRIPTION
**Pull request by eoger**
The reference browser will redirect manually to this page after completing an OAuth login flow.

### CODE REVIEW

**Comment by vladikoff** [comment]
context of this:


> basically in our fxa sample app. we’re redirecting to fxaclient:// which we mapped to an activity.
when building a browser, we don’t want to switch activities on success (same flow as in fennec), but just display that login was successful.
so, we’d still use fxaclient:// as a redirect and intercept to complete auth, but then show the success page in that tab. same page as in fennec.

cc @rfk

**Review by rfk — APPROVED** [review]
I think this is reasonable, but @shane-tomlinson may want to weigh in here as well.

**Comment by shane-tomlinson** [comment]
@vladikoff, @eoger - I'm summarizing to ensure I understand.

We want the flow to visually look the same as Fennec. But, because of the way OAuth works,
we have to get the OAuth code back to the browser, and to do so, we have to redirect. As soon
as we redirect, we lose the ability for FxA to display the "connect another device" page. To get around this, once we redirect to the browser, the browser then opens FxA's `/connect_another_device` page with the `?showSuccessMessage` and viola, the browser has it's OAuth code, and FxA displays the expected page.

**Comment by shane-tomlinson** [comment]
> the browser has the oauth code before opening this page.

Yeah, sorry, I should have worded that better.

**Review by shane-tomlinson — APPROVED** [review]
r+ - I'd rather use a relier to import search params where they can be validated, but the value passed in here is never displayed to the user, so... meh...

Thanks @eoger!

**Pull request merged**
