### PR TITLE
fix(form): On device disconnect,"Rather not say" is selected by default

### LINKED ISSUE #5277: On device disconnect, default "Rather not say" to selected
Let's save users a click when they disconnect devices by defaulting the "Rather not say" option to selected.

image

Why are users disconnecting devices in the past month?
* 2.1% - Suspicious device 
* 2.7% - Lost or stolen device 
* 41.1% - Old or replaced device 
* 30.1% - Duplicate device 
* 23.9% - Rather not way

We will want to remember this as numbers will change in the future.

### PR DESCRIPTION
**Pull request by apoorvasingh17**
<fix>(<app/scripts/templates/settings/client_disconnect.mustache>):<change made to the form under the heading Disconnect from Sync?:Rather not say option made the default option>

fixes #5277

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9e749da9e1f5ab4e1714640290515a91851b3ab
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Hey @apoorvasingh17 ! Could you please modify this test: https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/views/settings/client_disconnect.js#L106

And add a new assertion that this "Rather not Say" reason is checked by default when the view is rendered.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9e749da9e1f5ab4e1714640290515a91851b3ab
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: fee697eaf329537d55dd3a112d673eb0bdc31fa5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by apoorvasingh17** [comment]
@vladikoff I added the assertion but still the CI test failed.....where am I going wrong?

**Comment by shane-tomlinson** [comment]
> @vladikoff I added the assertion but still the CI test failed.....where am I going wrong?

@apoorvasingh17 - It looks like at least one unit test is failing. You should be able to run the unit tests locally by opening Firefox and browsing to https://127.0.0.1:3030/tests/index.html?coverage.
If all the tests pass (it takes ~1 min to run), then go to your dev console to the fxa-content-server subdirectory and type: `npm run test-travis`. That'll run the unit tests from within Selenium, sometimes tests pass running them directly and fail when run under Selenium.

**Comment by apoorvasingh17** [comment]
@shane-tomlinson The link is not opening. Does that mean there is some problem in the code? 
This is the assertion that I had added:    assert.ok($(view.el).find('input[name=disconnect-reasons][value=no]').prop('checked'), 'Rather not Say');

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson The link is not opening. Does that mean there is some problem in the code?

@apoorvasingh17 - this points to your servers not running, have you [installed and started the servers locally?](https://github.com/mozilla/fxa-content-server/#quick-start)?

[This is the test that is failing](https://github.com/mozilla/fxa-content-server/blob/08d29b4b8c4e90f594ded0ab45c66af87328bdfb/app/tests/spec/views/settings/client_disconnect.js#L135:L152). The test fails because the pre-condition no longer holds, the test checks that the form is initially disabled because no values are selected. Since a value is selected, the form should be enabled on render. That entire test can be removed, and instead, we should check whether view.enableForm is called fromwithin the `renders initial view` test.

[After the test that you added](https://github.com/mozilla/fxa-content-server/pull/5289/files#diff-7d7a5ecbbe8cf95929524bb7e2de1f1dR111), you should be able to check whether `view.enableForm` has been called. Before the view is rendered, you'll need to add a spy to `view.enableForm`, using `sinon.spy(view, 'enableForm')`. Spy's track whether a function has been called.

Hopefully this puts you on the right path, if you need any more help, please let me know!

**Comment by shane-tomlinson** [comment]
Hi @apoorvasingh17 - Other than the one failing test, this PR is in great shape. I think with a tad more effort, this will be ready to merge. Are you still interested? If you need a hand getting the servers installed/running, you can stop by our [IRC channel, #fxa on irc.mozilla.org](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Getting_Started_with_IRC). If no longer interested, let us know and we can take this PR as a base and give it a final nudge.

**Comment by apoorvasingh17** [comment]
@shane-tomlinson Yes I'm still interested and will resolve the issue as soon as I can. Sorry for the delay!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9e749da9e1f5ab4e1714640290515a91851b3ab
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: fee697eaf329537d55dd3a112d673eb0bdc31fa5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters

 * Commit: e611cb1a2df3a876ad2af14e98a516a16367dae4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a9e749da9e1f5ab4e1714640290515a91851b3ab
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: fee697eaf329537d55dd3a112d673eb0bdc31fa5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 100 characters

 * Commit: e611cb1a2df3a876ad2af14e98a516a16367dae4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f2827140e61088fb2932e7612347cec08c9f2695
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by apoorvasingh17** [comment]
@shane-tomlinson  I removed the block of code that was invalid and added the spy function yet the CI test is failing. Where am I going wrong?

**Comment by vladikoff** [comment]
Thank you @apoorvasingh17 !

**Pull request merged**
