### PR TITLE
feat(devices): use uid for devices panel

### PR DESCRIPTION
**Pull request by vladikoff**
@rfk r?

### CODE REVIEW

**Comment by rfk** [comment]
r+

**Comment by rfk** [comment]
Lol I remember this one from CircleCI: `Error: env: must be one of the possible values: ["production","development"]: value was "test"`

**Comment by vladikoff** [comment]
@rfk I guess they updated their image or something

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4c6ab13942b71c8385f54d8db45a8a6816ea9e02
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
ah yea we moved config to circle.yml

**Pull request merged**
