### PR TITLE
fix(token): end token code experiment for sync users

### PR DESCRIPTION
**Pull request by vbudhram**
This experiment has ran for over two weeks and we have enough data to proceed with analysis and conclusion. This PR ends the experiment.

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

**Comment by vladikoff** [comment]
Failed due to https://github.com/mozilla/fxa-content-server/pull/6004 for now, waiting for that to pass

**Comment by vbudhram** [comment]
@vladikoff Looks like this has been fixed up, r?

**Comment by vladikoff** [comment]
Thanks @vbudhram !

**Pull request merged**
