### PR TITLE
fix(deps): Update deps, remove nsp, add `npm audit` logging in travis 

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by vladikoff** [comment]
```
Running "nsp" task
Warning: Nsp.getFormatter is not a function Use --force to continue.
Aborted due to warnings.
```

**Comment by pdehaan** [comment]
FWIW, **nsp** is deprecated in favor of the new <kbd>npm audit</kbd> API:

> The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

**Comment by shane-tomlinson** [comment]
> FWIW, nsp is deprecated in favor of the new npm audit API:

That's exactly why I'm trying to do this. :D

**Comment by shane-tomlinson** [comment]
@mozilla/fxa-devs - r?

**Pull request merged**
