### PR TITLE
revert(csp): revert removing csp support for gravatar

### LINKED ISSUE #6127: Gavatar avatar images fail to load in settings
Noticed this today

screen shot 2018-04-26 at 4 18 25 pm

Avatars still load in iOS and desktop Firefox though.

### PR DESCRIPTION
**Pull request by vbudhram**
Fixes #6127 

Github complained when I tried to revert https://github.com/mozilla/fxa-content-server/pull/6015 (contents have changed). This manually reverts the changes.

### CODE REVIEW

**Comment by vladikoff** [comment]
Need nsp fixes

**Comment by vbudhram** [comment]
Travis seems to down?

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by shane-tomlinson** [comment]
> Travis seems to down?

I just gave it a kick, hopefully all green!

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

**Comment by shane-tomlinson** [comment]
@vbudhram - can you file a follow on issue to discuss how we should handle users that have a gravatar set?

**Comment by vbudhram** [comment]
@shane-tomlinson Thanks! Made https://github.com/mozilla/fxa-content-server/issues/6180 as follow up.

**Pull request merged**
