### PR TITLE
fix(style): improve legibility of body copy

### LINKED ISSUE #6632: Improve legibility of body copy by increasing line height
Currently our line height is equal to the font size.
screen shot 2018-10-10 at 3 14 12 pm

Using the [Golden Ratio Typography Calculator](https://grtcalculator.com) we can see that for content of this width, the line height should be 23px.
screen shot 2018-10-10 at 3 14 06 pm

Much better, no?

Would love to see this applied to our terms of service, and privacy policy (24px line height). Are there other areas with paragraphs of copy we can improve?

### PR DESCRIPTION
**Pull request by RPraneetha**
fixes #6632 

@shane-tomlinson Could I get a review, please?

### CODE REVIEW

**Comment by lmorchard** [comment]
@shane-tomlinson is probably swamped with work, so I can take a look at this too!

**Comment by RPraneetha** [comment]
Thanks, @lmorchard!

**Comment by lmorchard** [comment]
Looks good to me!

Before:

Capture

After:

Capture2

**Comment by ryanfeeley** [comment]
If I wasn't clear, I meant for this to be applied to the entire FxA website, not just this cookies page. Not feasible?

**Comment by lmorchard** [comment]
Ah yeah, sorry - I took the issue literally in reviewing here and just saw the cookies message and mention of legal pages. We can reopen, it's probably feasible

**Comment by SorinaFlorean** [comment]
Verified as fixed - stage Train 133.

**Pull request merged**
