### PR TITLE
fix(sign-in): Put registration links on left/top

### PR DESCRIPTION
**Pull request by ryanfeeley**
Putting registration links on left OR top (responsive) based on feedback that some users struggle to find the registration links.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef8d5edfa6a16809425a2f2ce4991172c0f46165
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
This broke the stacking: 
image

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f70deda800ea46dc3297c7efefc84cfcf6b91f07
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 549b0b740c9ed5dcdeb0dffbbe34d0c2ee5a369e
  * Your commit message body contains a line that is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
