### PR TITLE
chore(client): Standardize on [pP]arentView, replace [sS]uperView.

### LINKED ISSUE #3186: Code inconsistency ParentView, SuperView
Pick one.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #3186

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Slapping a WIP on this so nobody merges before the train is cut.

**Comment by shane-tomlinson** [comment]
The train has been cut, no longer WIP, @philbooth, yer it again!

**Comment by philbooth** [comment]
I'm going to make myself unpopular here.

Given that naming is important and we value consistency, I'm mildly uncomfortable with the dichotomy that this change introduces. `ParentView` and `ChildView` are a natural pair, as are `SubView` and `SuperView`. `ParentView` and `SubView`? Not so much.

I know you mentioned that changing `SubView` to `ChildView` has a much bigger footprint, but I think we should consider whether it is the right thing to do in the long run.

**Comment by shane-tomlinson** [comment]
@philbooth - I'm reading my thoughts echoed back several months later - https://github.com/mozilla/fxa-content-server/pull/2748#discussion_r36171754

**Comment by philbooth** [comment]
Now that #3195 does what it does, there is nothing that I disapprove of here. :+1:

**Pull request merged**
