### PR TITLE
fix(copy):Change passwords to logins 

### PR DESCRIPTION
**Pull request by MeridelW**
This is my first commit made in conjunction with @ryanfeeley. Please replace"Passwords" with "Logins" to be consistent with Firefox client.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0d0dcfdf3869391409ef5b78bf6645c623582749
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
@ryanfeeley please review

**Comment by MeridelW** [comment]
Thank you, both!

**Comment by vladikoff** [comment]
@MeridelW @ryanfeeley great work!

**Pull request merged**
