### PR TITLE
feat(locale): add Arabic locale support

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
100% complete https://pontoon.mozilla.org/ar/firefox-accounts/ 

@jrgm @vbudhram r?

**Comment by vbudhram** [comment]
LGTM 👍 

screen shot 2016-05-11 at 3 20 54 pm

**Comment by vladikoff** [comment]
Woohoo!

**Comment by mohamed7afezz** [comment]
I try to access https://accounts.stage.mozaws.net/ to test our localization but don't found Arabic version of FxA.Where can find it?
also there is some issues in RTL, Does this Arabic locale will publish direct in released servers? we need to test it before that.

**Comment by vladikoff** [comment]
Try https://latest.dev.lcip.org

**Pull request merged**
