### PR TITLE
fix(server): add extra body check for report error

### LINKED ISSUE #3708: Issues with server tests on Travis
Log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/127799377/log.txt

```
 TypeError: Object.keys called on non-object
```
part of `post-metrics-errors`.

Via: https://travis-ci.org/mozilla/fxa-content-server/jobs/127799377

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #3708

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram r?

**Comment by shane-tomlinson** [comment]
@vladikoff, @vbudhram - Will this need to be uplifted to train 61?

**Comment by vladikoff** [comment]
> Will this need to be uplifted to train 61?

Yeah we'll just do train 0.61.1 to include this and your functional test updates

**Comment by vbudhram** [comment]
This looks good 👍 , I am curious what value was passed into the body to cause to give `TypeError: Object.keys called on non-object`, since there was a check for null.

**Comment by vladikoff** [comment]
>  I am curious what value was passed into the body to cause to give 

Yeah it was some issue with node 0.10 only, node 4 was fine. strange!

**Pull request merged**
