### PR TITLE
fix(styles): replace clear sans with fira sans

### LINKED ISSUE #3643: Replace Clear Sans with Fira Sans weight of 200
Currently we're using two big web fonts. We should stick to the one we commissioned, Fira Sans. Weight of 200 seems to look good every (fictional screen attached).

screenshot 2016-04-06 15 21 11

Wanna have a go at it @johngruen?

### PR DESCRIPTION
**Pull request by ryanfeeley**
fixes #3643

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 34e9d03a878c998af1c405c2456d596bf538c209
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by pdehaan** [comment]
Me thinks something else is missing here, since we're possibly still loading/processing the Clear Sans font.
At a minimum, we may need to remove this package [/package.json:31](https://github.com/mozilla/fxa-content-server/blob/148f42a32e3192a61e3d9d3efef488ae841585b2/package.json#L31). Not sure what other Grunt tasks may need to be tweaked (apart from [./grunttasks/connect-fonts.js:15](https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/grunttasks/connect-fonts.js#L15) and [/grunttasks/connect-fonts.js:20](https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/grunttasks/connect-fonts.js#L20)).

**Comment by ryanfeeley** [comment]
@pdehaan Yes, this PR is definitely not ready for prime time. Vlad wanted me to file it so we don't lose it.

**Comment by pdehaan** [comment]
Also some [possible] test tweakage: [/tests/functional/fonts.js:33](https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/tests/functional/fonts.js#L33) and [/tests/functional/fonts.js:53](https://github.com/mozilla/fxa-content-server/blob/3b40424c1ccbce9dc142f6c0302811c422c697fa/tests/functional/fonts.js#L53).

**Disclaimer:**

**Comment by shane-tomlinson** [comment]
@ryanfeeley - do you want to continue working on this PR, or were you opening this to pass on?

**Comment by ryanfeeley** [comment]
@shane-tomlinson I'd like to pass it on. It's not wise for me to do this without @vladikoff on-site supervision, which will be rare this week. I have confirmed with the team that Fira Sans weight 200 is acceptable. The hard parts are stripping out the old fonts and optimizing Fira Sans 200 for download speeds.

**Comment by ryanfeeley** [comment]
Oh, and adding 2px of line height to most buttons so that the text is centered vertically.

**Comment by ryanfeeley** [comment]
Big buttons should name in 400 weight.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 34e9d03a878c998af1c405c2456d596bf538c209
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5092744a839a040041a61c8d5240c3cdc6825bbd
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
@shane-tomlinson could you please do a final check? 

We already checked the way stuff looks, just need to check if we removed everything.

**Comment by shane-tomlinson** [comment]
> 1,350 additions, 804 deletions not shown because the diff is too large. Please use a local Git client to view these changes. 

Woah, one line was deleted from the package.json file and 550 additional lines were added to npm-shrinkwrap.json. That seems odd.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I think this is a huge improvement in looks, a few minor nits while I was going through the screens:

### The show text is one px too high

show-1-px-too-high-43-looks-better

### The show text looks very light compared to the placeholder text

screen shot 2016-05-10 at 14 07 44

### The input text looks "heavy" when compared to the focused border

screen shot 2016-05-10 at 14 18 25

### The text looks "light" and the letter spacing in general looks "wide". Secondary links look almost too light.

screen shot 2016-05-10 at 14 08 42

screen shot 2016-05-10 at 14 09 09

### In contrast, the letter spacing looks too tight on settings page buttons

screen shot 2016-05-10 at 14 20 37

### The placeholder text in the change password flow looks HUGE

screen shot 2016-05-10 at 14 20 50


And a final question. If almost all of Mozilla web properties use Open Sans, why do we use Fira Sans? I find the discrepancy on the firstrun page jarring.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Fine eye appreciated!

> The show text is one px too high

I had originally thought so, but when @vladikoff and I tried it with other words (with descenders, like "g") it looked balanced. Can you try in another language and see if it's stlll off? If yes, please lower by 1px.

> The show text looks very light compared to the placeholder text

Is it because it's smaller?

> The input text looks "heavy" when compared to the focused border

That's okay. The text should definitely be more prominent.

> The text looks "light" and the letter spacing in general looks "wide". Secondary links look almost too light.

It is lighter, but deliberately so. I don't find that Fira Sans is great for most copy at normal weight. Primary buttons and a few other spots are the exception.

> In contrast, the letter spacing looks too tight on settings page buttons

It's just that the font currently lacks great kerning pairs so "ct" look cramped whereas "nc" looks too loose. Hopefully they can fix this at the font level.

> The placeholder text in the change password flow looks HUGE

Same as the other placeholders. Maybe the extra word makes it look bigger.

> And a final question. If almost all of Mozilla web properties use Open Sans, why do we use Fira Sans? I find the discrepancy on the firstrun page jarring.

We can't control what marketing does, but Fira Sans was created for Mozilla by one of the world's most famous type designers: https://en.wikipedia.org/wiki/Erik_Spiekermann

And while I prefer it more, Open Sans was created by Google, and associated with Google.

¯\_(ツ)_/¯

**Comment by shane-tomlinson** [comment]
Thanks for all the responses @ryanfeeley! If you think this is ready visually, so do I.

@vladikoff - assigning to you to understand the growth of npm-shrinkwrap.json even though a dependency was removed. Once that's understood, merge away!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5092744a839a040041a61c8d5240c3cdc6825bbd
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Did a cleaner shrinkwrap update! Thanks for **r**!

**Pull request merged**
