### PR TITLE
fix(sms): Clarify the "Why is this required" SMS text.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
Combine and simplify the first two sentences.

issue #4944

@ryanfeeley and @davismtl - is this what you had in mind? The title is still the same, but I replaced the first two sentences within the text with the suggested text.

screen shot 2017-05-04 at 12 16 00

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Ref #5026

**Comment by vladikoff** [comment]
Blocked!

**Comment by davismtl** [comment]
@ryanfeeley see below

I really don't like the 2nd paragraph. I re-wrote the first paragraph which is what we see here but we never touched the second one.

I would like something a bit more positive like:

For your privacy, Firefox cannot read your sync data because it is encrypted with your password. By syncing to another device, you ensure that you have a backup of your data even when you forget your password.

**Comment by ryanfeeley** [comment]
**Why sync multiple devices?**
The Sync service isn’t a permanent backup, it’s simply a secure way to transfer saved bookmarks, history and passwords between your own devices. You should install Firefox and sync at least two devices to protect against losing your data if you need to restore it but forget your password.

**Comment by vladikoff** [comment]
Continued in https://github.com/mozilla/fxa-content-server/pull/5138

**Pull request closed without merging**
