### PR TITLE
fix(iOS): Send the `login` message within the `visibilitychange`

### LINKED ISSUE #4377: User can close the FxA window in Fx for iOS before `login` message is sent.
In c04980db, we added a 5 second delay after completing signup/signin before sending the `login` notification to Fx for iOS. We did this so that users would see some messaging that says "go check your email" before Fx for iOS took over the screen and displayed its own messaging.

This delay gives the user a window of opportunity to close the FxA window before the `login` message is sent. If this happens, the browser is none the wiser of the user's login and will never start syncing.

If we can detect the window is about to close, maybe in a `beforeunload` handler, we should send the `login` message immediately.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
For verified accounts, the `login` message is sent immediately.

For unverified accounts, the `login` message is sent after the
first of 1) a 5 second timeout, or 2) a `blur` DOM event.

The `blur` DOM event is to handle the case where a user receives
their verification email and opens the email client before the timeout
has occurred.

For Fx for iOS >= 6.1, always send the `login` message immediately.

fixes #4377

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@vbudhram - mind doing a review of this, even before @st3fan has reported back his tests? I'd like to have the ducks lined up if he says "yeah, works as expected."

**Comment by shane-tomlinson** [comment]
This code is running on https://stomlinson.dev.lcip.org. I used the config from https://gist.github.com/shane-tomlinson/ac0e30442ebd9f32b13b449239319f60 to test on device

**Comment by shane-tomlinson** [comment]
fixes #4377

**Comment by vbudhram** [comment]
@shane-tomlinson On it 👍, I can also test with the ios patch and make sure all is well.

**Comment by shane-tomlinson** [comment]
> redirects to settings

Agh! That's not supposed to happen! It's supposed to redirect to `/signup_complete` I thought!

**Comment by vbudhram** [comment]
@shane-tomlinson Updates look r+! This performs exactly as we talked about. 

FxiOS 6.1 >=
* Polls until account is verified and then transitions to `/signup_complete`. User has to hit the top navigation `settings` button to get back to FxiOS settings screen. The user will show as connected in this page.

Merge at will!

**Pull request merged**
