### PR TITLE
fix(avatars): fixes Firefox 18 dataType json request

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
Will try to add a test

**Comment by shane-tomlinson** [comment]
For another PR, we may want to add a check in [xhr.js->ajax](https://github.com/mozilla/fxa-content-server/blob/2b472f30884c38bfb5444b2f09c9dbc4bb7c662d/app/scripts/lib/xhr.js#L29) to require a dataType, this has caught us a couple of times now (see #1786)

**Comment by vladikoff** [comment]
@zaach @shane-tomlinson r?

**Comment by shane-tomlinson** [comment]
Huh, works great in FF18, in nightly this is what I see - even after signing out or setting a new gravatar: 
screen shot 2015-02-02 at 20 28 48

**Comment by zaach** [comment]
Looks good for me on 18 and nightly. :+1:

**Pull request merged**
