### PR TITLE
this should fail gitcop

### PR DESCRIPTION
**Pull request by shane-tomlinson**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d5959443e170e3de995b19601b3ab402931eb873
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by shane-tomlinson** [comment]
Closing, this was only a test.

**Comment by pdehaan** [comment]
I wonder if we can modify the @GitCop auto-reply and add a helpful image:

**Comment by jrgm** [comment]
:+1:

**Pull request closed without merging**
