### PR TITLE
fix(reset): improve the reset password caveat copy

### LINKED ISSUE #2762: Improve the reset password caveat copy
Single device users with a new device are not grasping the gravity of the password reset. We hope they will try harder before doing a reset, so we have improved the copy.

reset-copy

* h1. Are you sure you want to reset your account password?
* small. Resetting your password will erase your browsing data from our servers. Any data on your devices will remain untouched. Begin the reset process by entering your email below.
* button. Begin reset
* link. Back

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2762

### CODE REVIEW

**Comment by vladikoff** [comment]
image

cc @ryanfeeley

**Comment by TDA** [comment]
@vladikoff Should it be "Any browsing data" instead of "Any data"?

**Comment by vladikoff** [comment]
> @vladikoff Should it be "Any browsing data" instead of "Any data"?

Not sure, @ryanfeeley wrote this :)

**Comment by ryanfeeley** [comment]
"Browsing data" is mentoned in the first sentence. "Data" is shorthand.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - are you happy with this? If so, can you hit the green button?

**Pull request merged**
