### PR TITLE
fix(logo): use new logo on terms and privacy pages

### LINKED ISSUE #5709: Static legal and terms pages have the old logo
Using Nightly, the links to the privacy and terms pages in Quantum first run still show the old logo.
- https://accounts.firefox.com/legal/privacy
- https://accounts.firefox.com/legal/terms

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #5709

@philbooth @vbudhram r? or anyone else

Quick fix for this until we switch to the new logo all the time

### CODE REVIEW

**Comment by vladikoff** [comment]
Wait hold on , it didn't work...

**Comment by vladikoff** [comment]
Ok should work now, sorry!

**Comment by vladikoff** [comment]
@vbudhram I thought after Nov 14 we can start removing the old logo

**Comment by rfk** [comment]
> I thought after Nov 14 we can start removing the old logo

Yep, pretty much any time after now should be fine.

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa-content-server/issues/5719

**Pull request merged**
