### PR TITLE
feat(tests): update user-agent in functional tests

### PR DESCRIPTION
**Pull request by vladikoff**
v40 is pretty old!

### CODE REVIEW

**Comment by vladikoff** [comment]
so with this, a bunch of functional tests go crazy because `fxaStatus` actually starts sending a logged in account data (from the browser). 

@shane-tomlinson we need to sit down and figure this one out probably...

**Comment by shane-tomlinson** [comment]
@vladikoff - you are right, this is going to wreck havoc. We could update the openPage listener to automatically listen for and respond to the `fxaccounts:fxa_status` event if no listener has already been defined, hopefully only a few tests would need to be updated then.

**Comment by shane-tomlinson** [comment]
There is more here, while I was running the functional tests the `fxaccounts:login` message needs to be handled in many cases too, the browser was actually signing in!

screenshot 2019-02-26 at 13 27 17
screenshot 2019-02-26 at 13 27 19

**Comment by vladikoff** [comment]
filed https://github.com/mozilla/fxa-content-server/issues/7012

**Pull request closed without merging**
