### PR TITLE
fix(htmllint): Fixes #5668 upgrade es6-promise to 4.2.4

### LINKED ISSUE #5668: [node8] failure running travis with htmllint
See https://travis-ci.org/mozilla/fxa-content-server/jobs/295573686#L4167-L4185

```
$ grunt htmllint:dist
Running "htmllint:dist" (htmllint) task
(node:9354) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

fxa-content-server.CRITICAL: uncaughtException TypeError: Array.prototype.slice called on null or undefined
  at slice (<anonymous>:null:null)
  at Function.Promise.all (/home/travis/build/mozilla/fxa-content-server/node_modules/promise/lib/es6-extensions.js:62:36)
  at Linter.lint (/home/travis/build/mozilla/fxa-content-server/node_modules/htmllint/lib/linter.js:58:20)
  at Linter.lint (/home/travis/build/mozilla/fxa-content-server/node_modules/promise/lib/node-extensions.js:38:17)
  at htmllint (/home/travis/build/mozilla/fxa-content-server/node_modules/htmllint/lib/index.js:11:24)
  at /home/travis/build/mozilla/fxa-content-server/node_modules/grunt-htmllint/tasks/htmllint.js:60:24
  at /home/travis/build/mozilla/fxa-content-server/node_modules/promise/lib/es6-extensions.js:18:19
  at flush (/home/travis/build/mozilla/fxa-content-server/node_modules/asap/asap.js:27:13)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at Function.Module.runMain (module.js:678:11)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3

Fatal error: Array.prototype.slice called on null or undefined
```

### PR DESCRIPTION
**Pull request by deeptibaghel**
#5668 [node8] failure running travis with htmllint: resolved after es6-promise upgrade to 4.2.4.

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Thanks @deeptibaghel, can you re-run `npm run shrink` with this change using npm@5? I merged https://github.com/mozilla/fxa-content-server/pull/6042 earlier today.

**Comment by deeptibaghel** [comment]
@shane-tomlinson i did, why does it generate so much of changes every time we run it ?

**Comment by shane-tomlinson** [comment]
@deeptibaghel - I can reproduce the +6700 lines if I run `npm shrinkwrap` instead of `npm run shrink`. [npmshrink](https://github.com/pdehaan/npmshrink) adds an `npm prune` to the process before running `npm shrinkwrap` and results in a cleaner npm-shrinkwrap.json.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 69a94e9c170f60f401df7646859ceb8d8a05a92e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
