### PR TITLE
fix(tests): better functional tests for age dropdowns

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by ckarlof** [comment]
Descriptive title please?

**Comment by vladikoff** [comment]
@shane-tomlinson I'm getting good results in several environments with this PR. Does this work for you?

**Comment by jrgm** [comment]
@vladikoff I'm getting good results on an ubuntu vm and on teamcity running against accounts.stage.mozaws.net.

**Comment by jrgm** [comment]
@vladikoff can you also land this on train-28?

**Comment by zaach** [comment]
Was the previous patch still a bit unstable?

**Comment by vladikoff** [comment]
@zaach yeah, especially for @shane-tomlinson locally

**Pull request merged**
