### PR TITLE
chore(travis): add npm -ls to travis file

### PR DESCRIPTION
**Pull request by pdehaan**

### CODE REVIEW

**Comment by pdehaan** [comment]
Inspired by https://github.com/mozilla/fxa-content-server/pull/2537 where Travis is failing, but I can pull @TDA's branch locally and the `grunt jscs` task passes flawlessly.

Not sure how people feel about adding `npm ls --depth 0` output into the Travis log, but feel free to check the log and see if this is remotely useful and/or helpful: https://travis-ci.org/mozilla/fxa-content-server/builds/66247672#L473

```sh
$ npm ls --depth 0
fxa-content-server@0.39.0 /home/travis/build/mozilla/fxa-content-server
├── awsbox@0.7.0
├── bluebird@2.2.2
├── body-parser@1.12.2
├── bower@1.4.1
├── connect-cachify@0.0.17
├── connect-fonts-clearsans@0.0.1
├── connect-fonts-firasans@0.0.4
├── connect-restreamer@1.0.0
├── consolidate@0.10.0
├── convict@0.8.0
├── cookie-parser@1.3.4
├── cors@2.6.0
├── coveralls@2.11.1
├── express@4.12.3
├── express-able@0.4.2
├── firefox-profile@0.3.3
├── grunt@0.4.5
├── grunt-amdcheck@1.3.1
├── grunt-autoprefixer@1.0.0
├── grunt-bump@0.0.15
├── grunt-cli@0.1.13
├── grunt-concurrent@0.5.0
├── grunt-connect-fonts@0.0.5
├── grunt-contrib-clean@0.6.0
├── grunt-contrib-concat@0.5.0
├── grunt-contrib-copy@0.5.0
├── grunt-contrib-csslint@0.2.0
├── grunt-contrib-cssmin@0.10.0
├── grunt-contrib-htmlmin@0.4.0
├── grunt-contrib-imagemin@0.9.2 (git://github.com/vladikoff/grunt-contrib-imagemin#2562d49676ade27842c92d93f60131269746cdb1)
├── grunt-contrib-jshint@0.10.0
├── grunt-contrib-uglify@0.5.1
├── grunt-contrib-watch@0.6.1
├── grunt-conventional-changelog@1.1.0
├── grunt-copyright@0.1.0
├── grunt-jscs@0.6.2
├── grunt-jsonlint@1.0.4
├── grunt-marked@0.1.1
├── grunt-nsp-shrinkwrap@0.0.3
├── grunt-po2json@0.2.0 (git://github.com/shane-tomlinson/grunt-po2json.git#c1a7406a0ba518612e80bfdffd450ab589dfd86d)
├── grunt-requirejs@0.4.2
├── grunt-rev@0.1.0
├── grunt-sass@0.18.1
├── grunt-text-replace@0.3.12
├── grunt-todo@0.4.0
├── grunt-usemin@2.3.0
├── grunt-z-schema@0.1.0
├── handlebars@1.3.0
├── helmet@0.7.1
├── http-proxy@1.11.1
├── i18n-abide@0.0.22
├── intern-geezer@2.1.1
├── jshint@2.5.3
├── jshint-stylish@0.4.0
├── jsxgettext-recursive@0.0.5
├── load-grunt-tasks@0.6.0
├── mkdirp@0.5.0
├── morgan@1.5.2
├── mozlog@1.0.1
├── node-statsd@0.1.1
├── request@2.40.0
├── serve-static@1.9.2
├── sync-exec@0.5.0
├── time-grunt@0.4.0
├── ua-parser@0.3.5
└── xmlhttprequest@1.5.1 (git://github.com/zaach/node-XMLHttpRequest.git#3f904613b860b4438e65a31b7b82f09a4d2d64dd)
```

**Comment by vladikoff** [comment]
can we collapse it into one line?

**Comment by pdehaan** [comment]
@vladikoff: I thought that travis would have done that automatically like with the other commands, but apparently not. I can see if there are any other output formats for `npm ls` or search for Travis docs on how to collapse output. Because... yeah, ~67 lines of output near the top isn't exactly pretty.

**Comment by vladikoff** [comment]
@pdehaan you can probably just pipe it using some unix magic

**Comment by pdehaan** [comment]
@vladikoff: OK, I figured out some TravisCI folding magic syntax:
https://travis-ci.org/mozilla/fxa-content-server/builds/66254204#L1158
Not ideal since it doesn't show the command, but you can force folding using `travis_fold:start:{token}` and `travis_fold:end:{token}` (where you can see that token in the right side of the travis log):

```yaml
 script:
  - travis_fold:start:npmls
  - npm ls --depth 0
  - travis_fold:end:npmls
```
(via https://github.com/travis-ci/travis-ci/issues/2158)

**Comment by zaach** [comment]
Newline stripping variant: `npm ls --depth 0 | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'`

**Comment by vladikoff** [comment]
@pdehaan could you update with https://github.com/mozilla/fxa-content-server/pull/2564#issuecomment-110848040 ?

**Comment by pdehaan** [comment]
@vladikoff: Done!
Output is now:

```
fxa-content-server@0.39.0 /home/travis/build/mozilla/fxa-content-server ├── awsbox@0.7.0 ├── bluebird@2.2.2 ├── body-parser@1.12.2 ├── bower@1.4.1 ├── connect-cachify@0.0.17 ├── connect-fonts-clearsans@0.0.1 ├── connect-fonts-firasans@0.0.4 ├── connect-restreamer@1.0.0 ├── consolidate@0.10.0 ├── convict@0.8.0 ├── cookie-parser@1.3.4 ├── cors@2.6.0 ├── coveralls@2.11.1 ├── express@4.12.3 ├── express-able@0.4.2 ├── firefox-profile@0.3.3 ├── grunt@0.4.5 ├── grunt-amdcheck@1.3.1 ├── grunt-autoprefixer@1.0.0 ├── grunt-bump@0.0.15 ├── grunt-cli@0.1.13 ├── grunt-concurrent@0.5.0 ├── grunt-connect-fonts@0.0.5 ├── grunt-contrib-clean@0.6.0 ├── grunt-contrib-concat@0.5.0 ├── grunt-contrib-copy@0.5.0 ├── grunt-contrib-csslint@0.2.0 ├── grunt-contrib-cssmin@0.10.0 ├── grunt-contrib-htmlmin@0.4.0 ├── grunt-contrib-imagemin@0.9.2 extraneous (git://github.com/vladikoff/grunt-contrib-imagemin#2562d49676ade27842c92d93f60131269746cdb1) ├── grunt-contrib-jshint@0.10.0 ├── grunt-contrib-uglify@0.5.1 ├── grunt-contrib-watch@0.6.1 ├── grunt-conventional-changelog@1.1.0 ├── grunt-copyright@0.1.0 ├── grunt-jscs@1.8.0 ├── grunt-jsonlint@1.0.4 ├── grunt-marked@0.1.1 ├── grunt-nsp-shrinkwrap@0.0.3 ├── grunt-po2json@0.2.0 (git://github.com/shane-tomlinson/grunt-po2json.git#c1a7406a0ba518612e80bfdffd450ab589dfd86d) ├── grunt-requirejs@0.4.2 ├── grunt-rev@0.1.0 ├── grunt-sass@0.18.1 ├── grunt-text-replace@0.3.12 ├── grunt-todo@0.4.0 ├── grunt-usemin@2.3.0 ├── grunt-z-schema@0.1.0 ├── handlebars@1.3.0 ├── helmet@0.7.1 ├── http-proxy@1.11.1 ├── i18n-abide@0.0.22 ├── intern-geezer@2.1.1 ├── jshint@2.5.3 ├── jshint-stylish@0.4.0 ├── jsxgettext-recursive@0.0.5 ├── load-grunt-tasks@0.6.0 ├── mkdirp@0.5.0 ├── morgan@1.5.2 ├── mozlog@1.0.1 ├── node-statsd@0.1.1 ├── request@2.40.0 ├── serve-static@1.9.2 ├── sync-exec@0.5.0 ├── time-grunt@0.4.0 ├── ua-parser@0.3.5 └── xmlhttprequest@1.5.1 (git://github.com/zaach/node-XMLHttpRequest.git#3f904613b860b4438e65a31b7b82f09a4d2d64dd) 
```

Tried digging into the docs, but didn't see an easy flag to remove whitespace or control output: https://docs.npmjs.com/cli/ls
All the flags just made the default output even more verbose.

So `sed` it is!

**Pull request merged**
