### PR TITLE
chore(deps): Bump request and universal-analytics dependencies

### LINKED ISSUE #3966: Patch for https://nodesecurity.io/advisories/130
According to NSP and https://nodesecurity.io/advisories/130, we have four vulnerable dependencies:

```
Running "nsp" task
Warning: (+) 4 vulnerabilities found
 Name           Installed   Patched   Path                                                                                                       
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > grunt-sass@1.1.0 > node-sass@3.8.0 > request@2.71.0 > tough-cookie@2.2.2       https://nodesecurity.io/advisories/130 
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > grunt-z-schema@0.1.0 > z-schema@2.4.10 > request@2.71.0 > tough-cookie@2.2.2   https://nodesecurity.io/advisories/130 
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > request@2.71.0 > tough-cookie@2.2.2                                            https://nodesecurity.io/advisories/130 
 tough-cookie   2.2.2       >=2.3.0   fxa-content-server@0.65.0 > universal-analytics@0.3.11 > request@2.71.0 > tough-cookie@2.2.2               https://nodesecurity.io/advisories/130 
 Use --force to continue.
```

We should patch this asap.
@vladikoff @pdehaan

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #3966

### CODE REVIEW

**Comment by pdehaan** [comment]
Hard to parse the Travis logs because of the parallel task behavior, but here's the TL;DR:

```sh
(+) No known vulnerabilities found
Done.

Execution Time (2016-07-23 02:47:32 UTC)
loading tasks  7.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
nsp            6.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 48%

The command "grunt nsp" exited with 0.
```

**Comment by TDA** [comment]
LGTM! Can be merged (asap too) 👍 Thanks @pdehaan !!

**Comment by pdehaan** [comment]
OK, resubmitted since I'm guessing this repo doesn't shrinkwrap devDependencies.
So I did `rm -rf node_modules npm-shrinkwrap.json && npm i --production` then `npm shrinkwrap` (using Node 4 and npm 2).

Hopefully everything is right this time, since shrinkwrap is a hassle and I was failing the pre-commit Git hook due to the fact that the required Grunt modules were no longer installed. So I re-pushed with `--no-verify` because I'm gangster.

**Comment by TDA** [comment]
@pdehaan Is this updated with the `shrinkwrap:prod` build?

**Pull request merged**
