### PR TITLE
feat(keys): add support to provide scoped keys

### PR DESCRIPTION
**Pull request by vladikoff**
Connects to https://github.com/mozilla/fxa-content-server/issues/5494

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 75f3eb30208d9277bb89172b2bb99d6cbd80fa40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 55b41ff16e46614118fde0218e0d1f91e906426d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d8da03a1f2ac58f25fde24d61becf08dcf9155e7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 292b1d23684c0c1780bc743edf1d735c7de43bdd
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 366c3c00a27339db01915d4c95534bde9adaa2df
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 75f3eb30208d9277bb89172b2bb99d6cbd80fa40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 55b41ff16e46614118fde0218e0d1f91e906426d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d8da03a1f2ac58f25fde24d61becf08dcf9155e7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 292b1d23684c0c1780bc743edf1d735c7de43bdd
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 366c3c00a27339db01915d4c95534bde9adaa2df
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 375a75452a9803158bed329310b3f054521a16aa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 14f58cae965f7b78d36853d8eea7cdade41cd361
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 191d7854b4dbc167ad2e9e5179459c6f88386fd8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b2eea97d6c60d46642e338ec7465dcead3e5ae58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 69519b5455045a7b7504e8fa46011b4da05fe5bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 375a75452a9803158bed329310b3f054521a16aa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 14f58cae965f7b78d36853d8eea7cdade41cd361
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 191d7854b4dbc167ad2e9e5179459c6f88386fd8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b2eea97d6c60d46642e338ec7465dcead3e5ae58
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 69519b5455045a7b7504e8fa46011b4da05fe5bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
Continued in https://github.com/mozilla/fxa-content-server/pull/5569

**Pull request closed without merging**
